<?php
require_once __DIR__.'/../config/config.php'; require_once __DIR__.'/../includes/session.php'; require_once __DIR__.'/../includes/auth.php';
require_login(); require_module_access($conn,'administration','view'); require_super();
function acnt(mysqli $c,string $s):int{$q=$c->query($s);return $q?(int)($q->fetch_assoc()['total']??0):0;}
$users=acnt($conn,"SELECT COUNT(*) total FROM users");
$super=acnt($conn,"SELECT COUNT(*) total FROM users WHERE is_super=1");
$modules=acnt($conn,"SELECT COUNT(*) total FROM access_modules");
include __DIR__.'/../includes/header.php'; include __DIR__.'/../includes/sidebar.php'; ?>
<style>
.ad{padding:28px 24px 42px;background:#f5f7fb;min-height:calc(100vh - 60px)}.as{max-width:1500px;margin:auto}.ah{background:linear-gradient(135deg,#273449,#475569);color:#fff;border-radius:18px;padding:28px 30px;display:flex;justify-content:space-between;align-items:center;gap:20px;margin-bottom:20px;box-shadow:0 12px 30px rgba(39,52,73,.2)}.ah h1{margin:5px 0;font-size:28px}.ah p{margin:0;color:rgba(255,255,255,.8);font-size:14px}.ak{font-size:11px;text-transform:uppercase;letter-spacing:1.5px;font-weight:800;color:#d6dee8}.am{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-bottom:20px}.ac{background:#fff;border:1px solid #e7ebf2;border-radius:14px;padding:20px;box-shadow:0 4px 14px rgba(31,45,61,.05)}.ac small{display:block;color:#7b8798;text-transform:uppercase;font-size:10px;font-weight:800}.ac strong{font-size:30px;color:#25324a}.ag{background:#fff;border:1px solid #e7ebf2;border-radius:14px;box-shadow:0 4px 16px rgba(31,45,61,.05);overflow:hidden}.ah2{padding:16px 20px;border-bottom:1px solid #edf0f5}.ab{padding:20px}.al{display:grid;grid-template-columns:1fr 1fr;gap:12px}.al a{padding:18px;border:1px solid #e7ebf2;border-radius:12px;text-decoration:none;color:#344054}.al a:hover{background:#f8fafc;text-decoration:none}.al i{color:#475569;margin-right:10px}@media(max-width:600px){.ad{padding:18px 12px}.ah{flex-direction:column;align-items:flex-start}.am,.al{grid-template-columns:1fr}}
</style>
<div class="ad"><div class="as"><div class="ah"><div><div class="ak">Administration</div><h1>Administration Dashboard</h1><p>Manage users, access rights, settings and system reports.</p></div><div><a href="../users/view_users.php" class="btn btn-light">Manage Users</a></div></div>
<div class="am"><a href="../users/view_users.php" class="ac text-decoration-none"><small>Total Users</small><strong><?= $users ?></strong></a><div class="ac"><small>Super Users</small><strong><?= $super ?></strong></div><div class="ac"><small>Access Modules</small><strong><?= $modules ?></strong></div></div>
<div class="ag"><div class="ah2"><strong>Administration</strong></div><div class="ab"><div class="al"><a href="../users/view_users.php"><i class="fas fa-users-cog"></i><strong>Manage Users</strong></a><a href="../users/access_rights.php"><i class="fas fa-user-shield"></i><strong>Access Rights</strong></a><a href="../settings/system_settings.php"><i class="fas fa-sliders-h"></i><strong>General Settings</strong></a><a href="../reports/sales_report.php"><i class="fas fa-chart-line"></i><strong>System Reports</strong></a></div></div></div>
</div></div><?php include __DIR__.'/../includes/footer.php'; ?>