<?php
require_once __DIR__.'/../config/config.php'; require_once __DIR__.'/../includes/session.php'; require_once __DIR__.'/../includes/auth.php';
require_login(); require_module_access($conn,'pharmacy','view');
function ph_count(mysqli $c,string $s):int{$q=$c->query($s);return $q?(int)($q->fetch_assoc()['total']??0):0;}
$queue=ph_count($conn,"SELECT COUNT(*) total FROM pharmacy_queue WHERE status='pending'");
$stock=ph_count($conn,"SELECT COUNT(*) total FROM pharmacy_stock");
$low=ph_count($conn,"SELECT COUNT(*) total FROM pharmacy_stock WHERE quantity<15");
$canCreate=can_module_action($conn,'pharmacy','create'); $canEdit=can_module_action($conn,'pharmacy','edit'); $canApprove=can_module_action($conn,'pharmacy','approve');
include __DIR__.'/../includes/header.php'; include __DIR__.'/../includes/sidebar.php'; ?>
<style>
.pd{padding:28px 24px 42px;background:#f5f7fb;min-height:calc(100vh - 60px)}.ps{max-width:1500px;margin:auto}.ph{background:linear-gradient(135deg,#087f5b,#0ca678);color:#fff;border-radius:18px;padding:28px 30px;display:flex;justify-content:space-between;align-items:center;gap:20px;margin-bottom:20px;box-shadow:0 12px 30px rgba(8,127,91,.2)}.ph h1{margin:5px 0;font-size:28px}.ph p{margin:0;color:rgba(255,255,255,.8);font-size:14px}.pk{font-size:11px;text-transform:uppercase;letter-spacing:1.5px;font-weight:800;color:#c8f7e7}.pm{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-bottom:20px}.pc{background:#fff;border:1px solid #e7ebf2;border-radius:14px;padding:20px;box-shadow:0 4px 14px rgba(31,45,61,.05)}.pc small{display:block;color:#7b8798;text-transform:uppercase;font-size:10px;font-weight:800}.pc strong{font-size:30px;color:#25324a}.pg{display:grid;grid-template-columns:2fr 1fr;gap:18px}.pp{background:#fff;border:1px solid #e7ebf2;border-radius:14px;overflow:hidden;box-shadow:0 4px 16px rgba(31,45,61,.05)}.pph{padding:16px 20px;border-bottom:1px solid #edf0f5}.ppb{padding:20px}.plinks{display:grid;grid-template-columns:1fr 1fr;gap:12px}.plinks a{padding:18px;border:1px solid #e7ebf2;border-radius:12px;text-decoration:none;color:#344054}.plinks a:hover{background:#f3fbf8;text-decoration:none}.plinks i{color:#0b8f67;margin-right:10px}@media(max-width:900px){.pg{grid-template-columns:1fr}}@media(max-width:600px){.pd{padding:18px 12px}.ph{flex-direction:column;align-items:flex-start}.pm{grid-template-columns:1fr}.plinks{grid-template-columns:1fr}}
</style>
<div class="pd"><div class="ps"><div class="ph"><div><div class="pk">Pharmacy</div><h1>Pharmacy Dashboard</h1><p>Track dispensing, stock and medicine sales from one workspace.</p></div><div><a href="dispensing_queue.php" class="btn btn-light">Dispensing Queue</a></div></div>
<div class="pm"><a href="dispensing_queue.php" class="pc text-decoration-none"><small>Pending Dispensing</small><strong><?= $queue ?></strong></a><a href="view_stock.php" class="pc text-decoration-none"><small>Stock Items</small><strong><?= $stock ?></strong></a><a href="view_stock.php" class="pc text-decoration-none"><small>Low Stock</small><strong><?= $low ?></strong></a></div>
<div class="pg"><div class="pp"><div class="pph"><strong>Pharmacy Operations</strong></div><div class="ppb"><div class="plinks"><a href="dispensing_queue.php"><i class="fas fa-clipboard-check"></i><strong>Dispensing Queue</strong></a><?php if($canCreate): ?><a href="sell_medicine.php"><i class="fas fa-prescription"></i><strong>Sell Medicine</strong></a><?php endif; ?><?php if($canEdit): ?><a href="add_stock.php"><i class="fas fa-box-open"></i><strong>Add Stock</strong></a><?php endif; ?><a href="view_stock.php"><i class="fas fa-capsules"></i><strong>View Stock</strong></a></div></div></div><div class="pp"><div class="pph"><strong>Queue</strong></div><div class="ppb"><h2><?= $queue ?></h2><small class="text-muted">prescriptions pending dispensing</small><?php if($canApprove): ?><a href="dispensing_queue.php" class="btn btn-primary btn-block mt-3">Open Queue</a><?php endif; ?></div></div></div>
</div></div><?php include __DIR__.'/../includes/footer.php'; ?>