-- HMS supply-chain hardening: PO -> GRN -> Inventory -> AP -> Supplier Payment
SET @db=DATABASE();

SET @sql=IF(NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='inventory_receipts' AND COLUMN_NAME='grn_no'),
'ALTER TABLE inventory_receipts ADD COLUMN grn_no VARCHAR(40) NULL AFTER id','SELECT 1');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

SET @sql=IF(NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='inventory_receipts' AND COLUMN_NAME='batch_no'),
'ALTER TABLE inventory_receipts ADD COLUMN batch_no VARCHAR(120) NULL AFTER supplier_invoice_no','SELECT 1');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

SET @sql=IF(NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='inventory_receipts' AND COLUMN_NAME='expiry_date'),
'ALTER TABLE inventory_receipts ADD COLUMN expiry_date DATE NULL AFTER batch_no','SELECT 1');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

SET @sql=IF(NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='inventory_receipts' AND COLUMN_NAME='store_name'),
'ALTER TABLE inventory_receipts ADD COLUMN store_name VARCHAR(120) NULL AFTER expiry_date','SELECT 1');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

SET @sql=IF(NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='inventory_receipts' AND COLUMN_NAME='remarks'),
'ALTER TABLE inventory_receipts ADD COLUMN remarks VARCHAR(255) NULL AFTER store_name','SELECT 1');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

SET @sql=IF(NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='inventory_receipts' AND COLUMN_NAME='created_at'),
'ALTER TABLE inventory_receipts ADD COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP','SELECT 1');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

SET @sql=IF(NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='inventory_receipts' AND INDEX_NAME='uq_inventory_receipts_grn'),
'CREATE UNIQUE INDEX uq_inventory_receipts_grn ON inventory_receipts(grn_no)','SELECT 1');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

SET @sql=IF(NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='supplier_payables' AND COLUMN_NAME='due_date'),
'ALTER TABLE supplier_payables ADD COLUMN due_date DATE NULL','SELECT 1');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

SET @sql=IF(NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='supplier_payments' AND COLUMN_NAME='transaction_reference'),
'ALTER TABLE supplier_payments ADD COLUMN transaction_reference VARCHAR(120) NULL','SELECT 1');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

-- Never allow duplicate AP for the same GRN.
SET @sql=IF(NOT EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='supplier_payables' AND INDEX_NAME='idx_sp_receipt_unique'),
'CREATE UNIQUE INDEX idx_sp_receipt_unique ON supplier_payables(receipt_id)','SELECT 1');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
