<?php
require_once __DIR__.'/../config/config.php'; require_once __DIR__.'/../includes/session.php'; require_once __DIR__.'/../includes/auth.php';
require_login(); require_module_access($conn,'finance','view');
function fcnt(mysqli $c,string $s):int{$q=$c->query($s);return $q?(int)($q->fetch_assoc()['total']??0):0;}
$open=fcnt($conn,"SELECT COUNT(*) total FROM cashier_shifts WHERE status='Open'");
$payments=fcnt($conn,"SELECT COUNT(*) total FROM payments WHERE DATE(created_at)=CURDATE()");
$unpaid=fcnt($conn,"SELECT COUNT(*) total FROM invoices WHERE status IN ('Unpaid','Partially Paid')");
$canView=can_module_action($conn,'finance','view');
include __DIR__.'/../includes/header.php'; include __DIR__.'/../includes/sidebar.php';
?>
<link rel="stylesheet" href="../assets/css/finance_modules.css">
<style>
.fd{padding:28px 24px 42px;background:#f5f7fb;min-height:calc(100vh - 60px)}.fs{max-width:1500px;margin:auto}.fh{background:linear-gradient(135deg,#063b73,#075b9d);color:#fff;border-radius:18px;padding:28px 30px;display:flex;justify-content:space-between;align-items:center;gap:20px;margin-bottom:20px;box-shadow:0 12px 30px rgba(6,59,115,.18)}.fh h1{margin:5px 0;font-size:28px}.fh p{margin:0;color:rgba(255,255,255,.8);font-size:14px}.fk{font-size:11px;text-transform:uppercase;letter-spacing:1.5px;font-weight:800;color:#c7edff}.fm{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-bottom:20px}.fc{background:#fff;border:1px solid #e7ebf2;border-radius:14px;padding:20px;box-shadow:0 4px 14px rgba(31,45,61,.05)}.fc small{display:block;color:#7b8798;text-transform:uppercase;font-size:10px;font-weight:800}.fc strong{font-size:30px;color:#25324a}.fg{display:grid;grid-template-columns:2fr 1fr;gap:18px}.fp{background:#fff;border:1px solid #e7ebf2;border-radius:14px;overflow:hidden;box-shadow:0 4px 16px rgba(31,45,61,.05)}.fph{padding:16px 20px;border-bottom:1px solid #edf0f5}.fpb{padding:20px}.fl{display:grid;grid-template-columns:1fr 1fr;gap:12px}.fl a{padding:18px;border:1px solid #e7ebf2;border-radius:12px;text-decoration:none;color:#344054}.fl a:hover{background:#f2fbff;text-decoration:none}.fl i{color:#075b9d;margin-right:10px}@media(max-width:900px){.fg{grid-template-columns:1fr}}@media(max-width:600px){.fd{padding:18px 12px}.fh{flex-direction:column;align-items:flex-start}.fm{grid-template-columns:1fr}.fl{grid-template-columns:1fr}}
</style>
<div class="fd"><div class="fs"><div class="fh"><div><div class="fk">Finance</div><h1>Finance Dashboard</h1><p>Monitor cashier operations, collections and receivables.</p></div><div><a href="../cashier/index.php" class="btn btn-light">Open Cashier</a></div></div>
<div class="fm"><a href="../cashier/shifts.php" class="fc text-decoration-none"><small>Open Cashier Shifts</small><strong><?= $open ?></strong></a><a href="../cashier/payment_history.php" class="fc text-decoration-none"><small>Payments Today</small><strong><?= $payments ?></strong></a><a href="../cashier/aged_receivables.php" class="fc text-decoration-none"><small>Outstanding Invoices</small><strong><?= $unpaid ?></strong></a></div>
<div class="fg"><div class="fp"><div class="fph"><strong>Finance Operations</strong></div><div class="fpb"><div class="fl"><a href="../cashier/index.php"><i class="fas fa-cash-register"></i><strong>Central Cashier</strong></a><a href="../cashier/shifts.php"><i class="fas fa-clock"></i><strong>Cashier Shifts</strong></a><a href="../cashier/aged_receivables.php"><i class="fas fa-user-clock"></i><strong>Aged Receivables</strong></a><a href="../cashier/payment_history.php"><i class="fas fa-receipt"></i><strong>Payment History</strong></a></div></div></div><div class="fp"><div class="fph"><strong>Receivables</strong></div><div class="fpb"><h2><?= $unpaid ?></h2><small class="text-muted">unpaid or partially paid invoices</small><a href="../cashier/aged_receivables.php" class="btn btn-primary btn-block mt-3">Open Receivables</a></div></div></div>
</div></div><?php include __DIR__.'/../includes/footer.php'; ?>