<?php
require_once __DIR__ . '/../config/config.php';
require_once __DIR__ . '/../includes/session.php';
require_once __DIR__ . '/../includes/auth.php';
require_login(); require_module_access($conn,'radiology','view');
function rad_count(mysqli $c,string $s):int{$q=$c->query($s);return $q?(int)($q->fetch_assoc()['total']??0):0;}
$pending=rad_count($conn,"SELECT COUNT(*) total FROM patient_services WHERE category='radiology' AND COALESCE(status,'Pending') NOT IN ('Completed','Cancelled')");
$today=rad_count($conn,"SELECT COUNT(*) total FROM patient_services WHERE category='radiology' AND DATE(created_at)=CURDATE()");
$done=rad_count($conn,"SELECT COUNT(*) total FROM patient_services WHERE category='radiology' AND status='Completed' AND DATE(created_at)=CURDATE()");
$canCreate=can_module_action($conn,'radiology','create'); $canApprove=can_module_action($conn,'radiology','approve');
include __DIR__.'/../includes/header.php'; include __DIR__.'/../includes/sidebar.php'; ?>
<style>
.rd{padding:28px 24px 42px;background:#f5f7fb;min-height:calc(100vh - 60px)}.rs{max-width:1500px;margin:auto}.rh{background:linear-gradient(135deg,#063b73,#075b9d);color:#fff;border-radius:18px;padding:28px 30px;display:flex;justify-content:space-between;gap:20px;align-items:center;margin-bottom:20px;box-shadow:0 12px 30px rgba(6,59,115,.18)}.rh h1{margin:5px 0;font-size:28px}.rh p{margin:0;color:rgba(255,255,255,.8);font-size:14px}.rk{font-size:11px;text-transform:uppercase;letter-spacing:1.5px;font-weight:800;color:#ddd0ff}.rm{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-bottom:20px}.rc{background:#fff;border:1px solid #e7ebf2;border-radius:14px;padding:20px;box-shadow:0 4px 14px rgba(31,45,61,.05)}.rc small{display:block;text-transform:uppercase;font-size:10px;font-weight:800;color:#7b8798}.rc strong{font-size:30px;color:#25324a}.rg{display:grid;grid-template-columns:2fr 1fr;gap:18px}.rp{background:#fff;border:1px solid #e7ebf2;border-radius:14px;overflow:hidden;box-shadow:0 4px 16px rgba(31,45,61,.05)}.rph{padding:16px 20px;border-bottom:1px solid #edf0f5}.rpb{padding:20px}.rl{display:grid;grid-template-columns:1fr 1fr;gap:12px}.rl a{padding:18px;border:1px solid #e7ebf2;border-radius:12px;text-decoration:none;color:#344054}.rl a:hover{background:#f5f9fd;text-decoration:none}.rl i{color:#075b9d;margin-right:10px}@media(max-width:900px){.rg{grid-template-columns:1fr}}@media(max-width:600px){.rd{padding:18px 12px}.rh{flex-direction:column;align-items:flex-start}.rm{grid-template-columns:1fr}.rl{grid-template-columns:1fr}}
</style>
<div class="rd"><div class="rs"><div class="rh"><div><div class="rk">Radiology</div><h1>Radiology Dashboard</h1><p>Manage imaging requests and results from one workspace.</p></div><div><?php if($canCreate): ?><a href="radiology_requests.php" class="btn btn-light">New Request</a><?php endif; ?> <a href="radiology_results.php" class="btn btn-outline-light">Results</a></div></div>
<div class="rm"><a href="radiology_results.php" class="rc text-decoration-none"><small>Pending Results</small><strong><?= $pending ?></strong></a><div class="rc"><small>Requests Today</small><strong><?= $today ?></strong></div><div class="rc"><small>Completed Today</small><strong><?= $done ?></strong></div></div>
<div class="rg"><div class="rp"><div class="rph"><strong>Radiology Operations</strong></div><div class="rpb"><div class="rl"><a href="radiology_requests.php"><i class="fas fa-x-ray"></i><strong>Requests</strong></a><a href="radiology_results.php"><i class="fas fa-images"></i><strong>Results</strong></a></div></div></div><div class="rp"><div class="rph"><strong>Queue</strong></div><div class="rpb"><h2 class="mb-1"><?= $pending ?></h2><small class="text-muted">items awaiting completion</small><?php if($canApprove): ?><a href="radiology_results.php" class="btn btn-primary btn-block mt-3">Open Results</a><?php endif; ?></div></div></div>
</div></div><?php include __DIR__.'/../includes/footer.php'; ?>