<?php
require_once __DIR__.'/../config/config.php'; require_once __DIR__.'/../includes/session.php'; require_once __DIR__.'/../includes/auth.php';
require_login(); require_module_access($conn,'hr_staff','view');
$canCreate=can_module_action($conn,'hr_staff','create'); $canEdit=can_module_action($conn,'hr_staff','edit'); $csrf=csrf_token();
$types=['Permanent','Fixed Term','Locum','Casual','Internship','Consultancy','Other']; $statuses=['Draft','Active','Renewed','Expired','Terminated']; $error=''; $message='';
$validDate=static function(string $v):bool { if($v==='')return true; $d=DateTime::createFromFormat('!Y-m-d',$v); return $d instanceof DateTime && $d->format('Y-m-d')===$v; };
if($_SERVER['REQUEST_METHOD']==='POST'){
 $id=(int)($_POST['id']??0);
 if(!verify_csrf_token($_POST['csrf_token']??null)) $error='Your security token expired. Refresh and try again.';
 elseif(($id>0&&!$canEdit)||($id===0&&!$canCreate)){http_response_code(403);exit('Forbidden: HR contract permission required.');}
 else{
  $staffId=(int)($_POST['staff_id']??0); $ref=trim((string)($_POST['contract_reference']??'')); $type=(string)($_POST['contract_type']??'Fixed Term'); $start=trim((string)($_POST['start_date']??'')); $end=trim((string)($_POST['end_date']??'')); $status=(string)($_POST['status']??'Active'); $notes=trim((string)($_POST['renewal_notes']??''));
  if($staffId<1||!in_array($type,$types,true)||!in_array($status,$statuses,true)||$start===''||!$validDate($start)||!$validDate($end)||($end!==''&&$end<$start)) $error='Choose a staff member and valid contract type, status and dates. End date cannot precede start date.';
  elseif(strlen($ref)>80||strlen($notes)>1000) $error='Contract reference or notes exceed the allowed length.';
  else{
   $check=$conn->prepare('SELECT id FROM hr_staff WHERE id=? LIMIT 1');
   if(!$check)$error='Unable to validate the staff record.';
   else{$check->bind_param('i',$staffId);$check->execute();$exists=$check->get_result()->fetch_assoc();$check->close();
    if(!$exists)$error='The selected staff record does not exist.';
    else{
     $refValue=$ref!==''?$ref:null; $endValue=$end!==''?$end:null; $notesValue=$notes!==''?$notes:null; $actor=(int)($_SESSION['user_id']??0);
     try{
      if($id>0){$stmt=$conn->prepare('UPDATE hr_staff_contracts SET staff_id=?,contract_reference=?,contract_type=?,start_date=?,end_date=?,status=?,renewal_notes=?,updated_by=? WHERE id=?');if(!$stmt)throw new RuntimeException('prepare update failed');$stmt->bind_param('issssssii',$staffId,$refValue,$type,$start,$endValue,$status,$notesValue,$actor,$id);$stmt->execute();$stmt->close();$message='Contract record updated.';if(function_exists('audit'))audit('hr_contract_updated','contract_id='.$id.',staff_id='.$staffId.',status='.$status);}
      else{$stmt=$conn->prepare('INSERT INTO hr_staff_contracts (staff_id,contract_reference,contract_type,start_date,end_date,status,renewal_notes,created_by,updated_by) VALUES (?,?,?,?,?,?,?,?,?)');if(!$stmt)throw new RuntimeException('prepare insert failed');$stmt->bind_param('issssssii',$staffId,$refValue,$type,$start,$endValue,$status,$notesValue,$actor,$actor);$stmt->execute();$newId=(int)$conn->insert_id;$stmt->close();$message='Contract record created.';if(function_exists('audit'))audit('hr_contract_created','contract_id='.$newId.',staff_id='.$staffId.',status='.$status);}
     }catch(Throwable $ex){error_log('HR contract save failed: '.$ex->getMessage());$error='Contract could not be saved. Check if the contract reference is already in use.';}
    }
   }
  }
 }
}
$edit=null;$editId=(int)($_GET['edit']??0);if($editId>0&&$canEdit){$st=$conn->prepare('SELECT * FROM hr_staff_contracts WHERE id=? LIMIT 1');if($st){$st->bind_param('i',$editId);$st->execute();$edit=$st->get_result()->fetch_assoc();$st->close();}}
$staff=$conn->query("SELECT id,staff_no,first_name,last_name,department FROM hr_staff WHERE status <> 'Separated' ORDER BY department,last_name");
$rows=$conn->query("SELECT c.*,s.staff_no,s.first_name,s.last_name,s.department,CASE WHEN c.status IN ('Terminated','Draft') THEN c.status WHEN c.end_date<CURDATE() THEN 'Expired' WHEN c.end_date<=DATE_ADD(CURDATE(),INTERVAL 60 DAY) THEN 'Renewal due' ELSE c.status END contract_state FROM hr_staff_contracts c JOIN hr_staff s ON s.id=c.staff_id ORDER BY CASE WHEN c.status IN ('Terminated','Draft') THEN 4 WHEN c.end_date<CURDATE() THEN 0 WHEN c.end_date<=DATE_ADD(CURDATE(),INTERVAL 60 DAY) THEN 1 ELSE 2 END,c.end_date,s.last_name");
$summary=$conn->query("SELECT COUNT(*) total,SUM(status='Active' AND end_date<CURDATE()) expired,SUM(status='Active' AND end_date BETWEEN CURDATE() AND DATE_ADD(CURDATE(),INTERVAL 60 DAY)) due FROM hr_staff_contracts");$counts=$summary?$summary->fetch_assoc():['total'=>0,'expired'=>0,'due'=>0];
$e=static fn($v)=>htmlspecialchars((string)($v??''),ENT_QUOTES,'UTF-8'); include __DIR__.'/../includes/header.php'; include __DIR__.'/../includes/sidebar.php';
?>
<style>
.hct{padding:26px 22px 48px;background:#f3f6fb;min-height:calc(100vh - 75px)}.hct-wrap{max-width:1450px;margin:auto}.hct-hero{padding:25px 28px;border-radius:18px;color:#fff;background:linear-gradient(125deg,#083d7b,#1264bd 60%,#13a8b8);margin-bottom:18px;display:flex;justify-content:space-between;gap:14px;align-items:center;flex-wrap:wrap}.hct-hero h2{margin:0;color:#fff;font-size:1.7rem;font-weight:800}.hct-hero p{margin:7px 0 0;color:#e1efff}.hct-card,.hct-metric{background:#fff;border:1px solid #e1e8f0;border-radius:15px;box-shadow:0 5px 20px #1428460d;margin-bottom:17px;overflow:hidden}.hct-head{padding:15px 19px;border-bottom:1px solid #e9eef4;font-weight:800;color:#172b45}.hct-metrics{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:13px;margin-bottom:17px}.hct-metric{padding:17px}.hct-metric small{display:block;color:#68778b;text-transform:uppercase;font-size:.68rem;font-weight:800}.hct-metric strong{display:block;font-size:1.5rem;color:#172b45;margin-top:6px}.hct-form{padding:19px;display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:13px}.hct-field label{display:block;font-size:.68rem;text-transform:uppercase;font-weight:800;color:#65748a;margin-bottom:6px}.hct-field input,.hct-field select,.hct-field textarea{width:100%;border:1px solid #d6e0eb;border-radius:9px;padding:10px 11px;background:#fff}.hct-wide{grid-column:1/-1}.hct-btn{border:0;border-radius:9px;padding:10px 13px;font-weight:800;display:inline-flex;align-items:center;gap:7px;text-decoration:none;cursor:pointer}.hct-primary{background:#104d91;color:#fff}.hct-muted{background:#edf3fa;color:#24415f}.hct-alert{padding:12px 15px;border-radius:9px;margin-bottom:14px;font-weight:700}.hct-error{background:#fff1f1;color:#a11}.hct-success{background:#ecfdf5;color:#087443}.hct-tablewrap{overflow:auto}.hct-table{width:100%;border-collapse:collapse;min-width:900px}.hct-table th,.hct-table td{text-align:left;padding:12px 14px;border-bottom:1px solid #edf1f5;font-size:.83rem}.hct-table th{background:#f7f9fc;color:#68778b;text-transform:uppercase;font-size:.65rem;letter-spacing:.05em}.hct-name{font-weight:800;color:#172b45}.hct-sub{display:block;color:#77869a;font-size:.74rem;margin-top:3px}.hct-pill{display:inline-block;padding:5px 8px;border-radius:99px;background:#edf2f7;color:#475569;font-size:.66rem;font-weight:800}.hct-current{background:#e9fbf1;color:#087443}.hct-expired{background:#fff0f0;color:#a22}.hct-soon{background:#fff7e6;color:#996300}@media(max-width:800px){.hct-form{grid-template-columns:repeat(2,minmax(0,1fr))}@media(max-width:560px){.hct{padding:16px 11px}.hct-form,.hct-metrics{grid-template-columns:1fr}.hct-hero{padding:20px}}
</style>
<div class="hct"><div class="hct-wrap"><section class="hct-hero"><div><div style="font-size:.68rem;letter-spacing:.14em;text-transform:uppercase;font-weight:800;margin-bottom:6px">People operations · Employment lifecycle</div><h2>Contract Register</h2><p>Track contract dates, renewal deadlines and agreement status.</p></div><a class="hct-btn" style="background:#fff;color:#0b4e8b" href="/hospital_system/hr/index.php"><i class="fas fa-arrow-left"></i> Staff Directory</a></section>
<?php if($error!==''):?><div class="hct-alert hct-error"><?= $e($error) ?></div><?php endif;?><?php if($message!==''):?><div class="hct-alert hct-success"><?= $e($message) ?></div><?php endif;?>
<section class="hct-metrics"><div class="hct-metric"><small>Contract records</small><strong><?= (int)($counts['total']??0) ?></strong></div><div class="hct-metric"><small>Expired active contracts</small><strong><?= (int)($counts['expired']??0) ?></strong></div><div class="hct-metric"><small>Active contracts ending in 60 days</small><strong><?= (int)($counts['due']??0) ?></strong></div></section>
<?php if(($canCreate&&!$edit)||($edit&&$canEdit)):?><section class="hct-card"><div class="hct-head"><?= $edit?'Edit contract':'Add contract' ?></div><form method="post" class="hct-form"><input type="hidden" name="csrf_token" value="<?= $e($csrf) ?>"><input type="hidden" name="id" value="<?= (int)($edit['id']??0) ?>">
<div class="hct-field"><label>Staff member *</label><select name="staff_id" required><option value="">Select employee</option><?php if($staff):while($s=$staff->fetch_assoc()):?><option value="<?= (int)$s['id'] ?>" <?= ((int)($edit['staff_id']??0)===(int)$s['id'])?'selected':'' ?>><?= $e(($s['staff_no']?:'STAFF').' · '.$s['first_name'].' '.$s['last_name'].' — '.$s['department']) ?></option><?php endwhile;$staff->data_seek(0);endif;?></select></div>
<div class="hct-field"><label>Contract reference</label><input name="contract_reference" maxlength="80" value="<?= $e($edit['contract_reference']??'') ?>" placeholder="Optional internal reference"></div><div class="hct-field"><label>Contract type</label><select name="contract_type"><?php foreach($types as $t):?><option value="<?= $e($t) ?>" <?= (($edit['contract_type']??'Fixed Term')===$t)?'selected':'' ?>><?= $e($t) ?></option><?php endforeach;?></select></div>
<div class="hct-field"><label>Start date *</label><input type="date" name="start_date" required value="<?= $e($edit['start_date']??'') ?>"></div><div class="hct-field"><label>End date</label><input type="date" name="end_date" value="<?= $e($edit['end_date']??'') ?>"></div><div class="hct-field"><label>Record status</label><select name="status"><?php foreach($statuses as $st):?><option value="<?= $e($st) ?>" <?= (($edit['status']??'Active')===$st)?'selected':'' ?>><?= $e($st) ?></option><?php endforeach;?></select></div>
<div class="hct-field hct-wide"><label>Renewal / HR notes</label><textarea name="renewal_notes" maxlength="1000"><?= $e($edit['renewal_notes']??'') ?></textarea></div><div class="hct-wide"><button class="hct-btn hct-primary" type="submit"><i class="fas fa-save"></i> Save contract</button><?php if($edit):?> <a class="hct-btn hct-muted" href="contracts.php">Cancel</a><?php endif;?></div></form></section><?php endif;?>
<section class="hct-card"><div class="hct-head">Contracts · expiry and renewal exceptions first</div><div class="hct-tablewrap"><table class="hct-table"><thead><tr><th>Staff member</th><th>Reference / type</th><th>Dates</th><th>Status</th><th>Renewal notes</th><th>Action</th></tr></thead><tbody><?php if($rows&&$rows->num_rows):while($r=$rows->fetch_assoc()):$state=(string)$r['contract_state'];$cls=$state==='Expired'?'hct-expired':($state==='Renewal due'?'hct-soon':(in_array($state,['Active','Renewed'],true)?'hct-current':''));?><tr><td><span class="hct-name"><?= $e($r['first_name'].' '.$r['last_name']) ?></span><span class="hct-sub"><?= $e($r['staff_no'].' · '.$r['department']) ?></span></td><td><?= $e($r['contract_reference']?:'No reference') ?><span class="hct-sub"><?= $e($r['contract_type']) ?></span></td><td><?= $e($r['start_date']) ?><span class="hct-sub">Ends: <?= $e($r['end_date']?:'No end date') ?></span></td><td><span class="hct-pill <?= $cls ?>"><?= $e($state) ?></span></td><td><?= $e($r['renewal_notes']?:'—') ?></td><td><?php if($canEdit):?><a class="hct-btn hct-muted" href="?edit=<?= (int)$r['id'] ?>"><i class="fas fa-pen"></i> Edit</a><?php else:?>—<?php endif;?></td></tr><?php endwhile;else:?><tr><td colspan="6" style="text-align:center;padding:32px;color:#77869a">No contract records yet. Add current agreements to monitor renewal dates.</td></tr><?php endif;?></tbody></table></div></section></div></div>
