<?php
require_once __DIR__.'/../config/config.php'; require_once __DIR__.'/../includes/session.php'; require_once __DIR__.'/../includes/auth.php';
require_login(); require_module_access($conn,'hr_staff','view');
$canCreate=can_module_action($conn,'hr_staff','create');$canEdit=can_module_action($conn,'hr_staff','edit');$csrf=csrf_token();$error='';$message='';
$types=['Resignation','End of Contract','Termination','Retirement','Redundancy','Death','Other'];$statuses=['In Progress','Completed','Cancelled'];
$checks=['handover_completed'=>'Handover completed','assets_returned'=>'Company assets returned','access_revoked'=>'System access revoked','finance_clearance'=>'Finance clearance completed','exit_interview'=>'Exit interview completed'];
$validDate=static function(string $v):bool{if($v==='')return true;$d=DateTime::createFromFormat('!Y-m-d',$v);return $d instanceof DateTime&&$d->format('Y-m-d')===$v;};
if($_SERVER['REQUEST_METHOD']==='POST'){
 $id=(int)($_POST['id']??0);
 if(!verify_csrf_token($_POST['csrf_token']??null))$error='Your security token expired. Refresh and try again.';
 elseif(($id>0&&!$canEdit)||($id===0&&!$canCreate)){http_response_code(403);exit('Forbidden: HR separation permission required.');}
 else{
  $staffId=(int)($_POST['staff_id']??0);$type=(string)($_POST['separation_type']??'Resignation');$notice=trim((string)($_POST['notice_date']??''));$last=trim((string)($_POST['last_working_date']??''));$reason=trim((string)($_POST['reason']??''));$status=(string)($_POST['status']??'In Progress');$notes=trim((string)($_POST['notes']??''));$flags=[];foreach($checks as $key=>$label)$flags[$key]=isset($_POST[$key])?1:0;
  if($staffId<1||!in_array($type,$types,true)||!in_array($status,$statuses,true)||$last===''||!$validDate($last)||!$validDate($notice)||($notice!==''&&$notice>$last))$error='Select a staff member, separation type and valid dates. Notice date cannot be after the last working date.';
  elseif(strlen($reason)>500||strlen($notes)>1500)$error='Reason or notes exceed the allowed length.';
  elseif($status==='Completed'&&array_sum($flags)!==count($checks))$error='An offboarding case cannot be completed until all five clearance checks are confirmed.';
  else{
   $conn->begin_transaction();
   try{
    $lock=$conn->prepare('SELECT id,status FROM hr_staff WHERE id=? FOR UPDATE');if(!$lock)throw new RuntimeException('staff lock prepare failed');$lock->bind_param('i',$staffId);$lock->execute();$staffRow=$lock->get_result()->fetch_assoc();$lock->close();if(!$staffRow)throw new InvalidArgumentException('Selected staff record was not found.');
    if($id>0){$old=$conn->prepare('SELECT status FROM hr_staff_separations WHERE id=? FOR UPDATE');if(!$old)throw new RuntimeException('case lock prepare failed');$old->bind_param('i',$id);$old->execute();$oldRow=$old->get_result()->fetch_assoc();$old->close();if(!$oldRow)throw new InvalidArgumentException('Offboarding case was not found.');if($oldRow['status']==='Completed'&&$status!=='Completed')throw new InvalidArgumentException('A completed offboarding case cannot be reopened or cancelled. Contact an administrator for correction.');}
    $noticeValue=$notice!==''?$notice:null;$reasonValue=$reason!==''?$reason:null;$notesValue=$notes!==''?$notes:null;$actor=(int)($_SESSION['user_id']??0);
    if($id>0){$sql='UPDATE hr_staff_separations SET staff_id=?,separation_type=?,notice_date=?,last_working_date=?,reason=?,status=?,handover_completed=?,assets_returned=?,access_revoked=?,finance_clearance=?,exit_interview=?,notes=?,updated_by=?,completed_at=CASE WHEN ?="Completed" THEN COALESCE(completed_at,NOW()) ELSE NULL END WHERE id=?';$st=$conn->prepare($sql);if(!$st)throw new RuntimeException('case update prepare failed');$st->bind_param('isssssiiiiisisi',$staffId,$type,$noticeValue,$last,$reasonValue,$status,$flags['handover_completed'],$flags['assets_returned'],$flags['access_revoked'],$flags['finance_clearance'],$flags['exit_interview'],$notesValue,$actor,$status,$id);$st->execute();$st->close();$caseId=$id;}
    else{$sql='INSERT INTO hr_staff_separations (staff_id,separation_type,notice_date,last_working_date,reason,status,handover_completed,assets_returned,access_revoked,finance_clearance,exit_interview,notes,created_by,updated_by,completed_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,IF(?="Completed",NOW(),NULL))';$st=$conn->prepare($sql);if(!$st)throw new RuntimeException('case insert prepare failed');$st->bind_param('isssssiiiiisiis',$staffId,$type,$noticeValue,$last,$reasonValue,$status,$flags['handover_completed'],$flags['assets_returned'],$flags['access_revoked'],$flags['finance_clearance'],$flags['exit_interview'],$notesValue,$actor,$actor,$status);$st->execute();$caseId=(int)$conn->insert_id;$st->close();}
    if($status==='Completed'){$up=$conn->prepare("UPDATE hr_staff SET status='Separated',updated_by=? WHERE id=?");if(!$up)throw new RuntimeException('staff status update prepare failed');$up->bind_param('ii',$actor,$staffId);$up->execute();$up->close();}
    if(function_exists('audit'))audit('hr_separation_saved','case_id='.$caseId.',staff_id='.$staffId.',status='.$status);
    $conn->commit();$message=$status==='Completed'?'Offboarding completed; staff status changed to Separated.':'Offboarding case saved.';
   }catch(Throwable $ex){$conn->rollback();if($ex instanceof InvalidArgumentException)$error=$ex->getMessage();else{error_log('HR offboarding save failed: '.$ex->getMessage());$error='Offboarding could not be saved. Review the record and try again.';}}
  }
 }
}
$edit=null;$editId=(int)($_GET['edit']??0);if($editId>0&&$canEdit){$st=$conn->prepare('SELECT * FROM hr_staff_separations WHERE id=? LIMIT 1');if($st){$st->bind_param('i',$editId);$st->execute();$edit=$st->get_result()->fetch_assoc();$st->close();}}
$staff=$conn->query("SELECT id,staff_no,first_name,last_name,department FROM hr_staff WHERE status <> 'Separated' ORDER BY department,last_name");
$rows=$conn->query('SELECT x.*,s.staff_no,s.first_name,s.last_name,s.department FROM hr_staff_separations x JOIN hr_staff s ON s.id=x.staff_id ORDER BY FIELD(x.status,\'In Progress\',\'Completed\',\'Cancelled\'),x.last_working_date DESC');
$summary=$conn->query("SELECT COUNT(*) total,SUM(status='In Progress') pending,SUM(status='Completed') completed FROM hr_staff_separations");$counts=$summary?$summary->fetch_assoc():['total'=>0,'pending'=>0,'completed'=>0];
$e=static fn($v)=>htmlspecialchars((string)($v??''),ENT_QUOTES,'UTF-8');include __DIR__.'/../includes/header.php';include __DIR__.'/../includes/sidebar.php';
?>
<style>
.hro{padding:26px 22px 48px;background:#f3f6fb;min-height:calc(100vh - 75px)}.hro-wrap{max-width:1450px;margin:auto}.hro-hero{padding:25px 28px;border-radius:18px;color:#fff;background:linear-gradient(125deg,#083d7b,#1264bd 60%,#13a8b8);margin-bottom:18px;display:flex;justify-content:space-between;gap:14px;align-items:center;flex-wrap:wrap}.hro-hero h2{margin:0;color:#fff;font-size:1.7rem;font-weight:800}.hro-hero p{margin:7px 0 0;color:#e1efff}.hro-card,.hro-metric{background:#fff;border:1px solid #e1e8f0;border-radius:15px;box-shadow:0 5px 20px #1428460d;margin-bottom:17px;overflow:hidden}.hro-head{padding:15px 19px;border-bottom:1px solid #e9eef4;font-weight:800;color:#172b45}.hro-metrics{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:13px;margin-bottom:17px}.hro-metric{padding:17px}.hro-metric small{display:block;color:#68778b;text-transform:uppercase;font-size:.68rem;font-weight:800}.hro-metric strong{display:block;font-size:1.5rem;color:#172b45;margin-top:6px}.hro-form{padding:19px;display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:13px}.hro-field label{display:block;font-size:.68rem;text-transform:uppercase;font-weight:800;color:#65748a;margin-bottom:6px}.hro-field input,.hro-field select,.hro-field textarea{width:100%;border:1px solid #d6e0eb;border-radius:9px;padding:10px 11px;background:#fff}.hro-wide{grid-column:1/-1}.hro-checks{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.hro-check{padding:12px;border:1px solid #e1e8f0;border-radius:10px;display:flex;gap:9px;align-items:center;color:#35465d;font-weight:700}.hro-btn{border:0;border-radius:9px;padding:10px 13px;font-weight:800;display:inline-flex;align-items:center;gap:7px;text-decoration:none;cursor:pointer}.hro-primary{background:#104d91;color:#fff}.hro-muted{background:#edf3fa;color:#24415f}.hro-alert{padding:12px 15px;border-radius:9px;margin-bottom:14px;font-weight:700}.hro-error{background:#fff1f1;color:#a11}.hro-success{background:#ecfdf5;color:#087443}.hro-tablewrap{overflow:auto}.hro-table{width:100%;border-collapse:collapse;min-width:950px}.hro-table th,.hro-table td{text-align:left;padding:12px 14px;border-bottom:1px solid #edf1f5;font-size:.83rem}.hro-table th{background:#f7f9fc;color:#68778b;text-transform:uppercase;font-size:.65rem}.hro-name{font-weight:800;color:#172b45}.hro-sub{display:block;color:#77869a;font-size:.74rem;margin-top:3px}.hro-pill{display:inline-block;padding:5px 8px;border-radius:99px;background:#edf2f7;color:#475569;font-size:.66rem;font-weight:800}.hro-done{background:#e9fbf1;color:#087443}.hro-pending{background:#fff7e6;color:#996300}@media(max-width:800px){.hro-form{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:560px){.hro{padding:16px 11px}.hro-form,.hro-metrics,.hro-checks{grid-template-columns:1fr}.hro-hero{padding:20px}}
</style>
<div class="hro"><div class="hro-wrap"><section class="hro-hero"><div><div style="font-size:.68rem;letter-spacing:.14em;text-transform:uppercase;font-weight:800;margin-bottom:6px">People operations · Employment lifecycle</div><h2>Staff Offboarding</h2><p>Track handover, assets, access revocation and clearance before separation is closed.</p></div><a class="hro-btn" style="background:#fff;color:#0b4e8b" href="/hospital_system/hr/index.php"><i class="fas fa-arrow-left"></i> Staff Directory</a></section>
<?php if($error!==''):?><div class="hro-alert hro-error"><?= $e($error) ?></div><?php endif;?><?php if($message!==''):?><div class="hro-alert hro-success"><?= $e($message) ?></div><?php endif;?>
<section class="hro-metrics"><div class="hro-metric"><small>Total separation cases</small><strong><?= (int)($counts['total']??0) ?></strong></div><div class="hro-metric"><small>In progress</small><strong><?= (int)($counts['pending']??0) ?></strong></div><div class="hro-metric"><small>Completed</small><strong><?= (int)($counts['completed']??0) ?></strong></div></section>
<?php if(($canCreate&&!$edit)||($edit&&$canEdit)):?><section class="hro-card"><div class="hro-head"><?= $edit?'Update offboarding case':'Start offboarding case' ?></div><form method="post" class="hro-form"><input type="hidden" name="csrf_token" value="<?= $e($csrf) ?>"><input type="hidden" name="id" value="<?= (int)($edit['id']??0) ?>">
<div class="hro-field"><label>Staff member *</label><select name="staff_id" required><option value="">Select employee</option><?php if($staff):while($s=$staff->fetch_assoc()):?><option value="<?= (int)$s['id'] ?>" <?= ((int)($edit['staff_id']??0)===(int)$s['id'])?'selected':'' ?>><?= $e(($s['staff_no']?:'STAFF').' · '.$s['first_name'].' '.$s['last_name'].' — '.$s['department']) ?></option><?php endwhile;$staff->data_seek(0);endif;?></select></div>
<div class="hro-field"><label>Separation type</label><select name="separation_type"><?php foreach($types as $t):?><option value="<?= $e($t) ?>" <?= (($edit['separation_type']??'Resignation')===$t)?'selected':'' ?>><?= $e($t) ?></option><?php endforeach;?></select></div><div class="hro-field"><label>Case status</label><select name="status"><?php foreach($statuses as $st):?><option value="<?= $e($st) ?>" <?= (($edit['status']??'In Progress')===$st)?'selected':'' ?>><?= $e($st) ?></option><?php endforeach;?></select></div>
<div class="hro-field"><label>Notice date</label><input type="date" name="notice_date" value="<?= $e($edit['notice_date']??'') ?>"></div><div class="hro-field"><label>Last working date *</label><input type="date" name="last_working_date" required value="<?= $e($edit['last_working_date']??'') ?>"></div><div class="hro-field"><label>Reason</label><input name="reason" maxlength="500" value="<?= $e($edit['reason']??'') ?>"></div>
<div class="hro-wide"><div class="hro-head" style="padding:0 0 10px;border:0">Clearance checklist · all five required to complete</div><div class="hro-checks"><?php foreach($checks as $key=>$label):?><label class="hro-check"><input type="checkbox" name="<?= $e($key) ?>" value="1" <?= !empty($edit[$key])?'checked':'' ?>><?= $e($label) ?></label><?php endforeach;?></div></div>
<div class="hro-field hro-wide"><label>Handover / HR notes</label><textarea name="notes" maxlength="1500"><?= $e($edit['notes']??'') ?></textarea></div><div class="hro-wide"><button class="hro-btn hro-primary" type="submit"><i class="fas fa-save"></i> Save offboarding case</button><?php if($edit):?> <a class="hro-btn hro-muted" href="offboarding.php">Cancel</a><?php endif;?></div></form></section><?php endif;?>
<section class="hro-card"><div class="hro-head">Separation register</div><div class="hro-tablewrap"><table class="hro-table"><thead><tr><th>Staff member</th><th>Type / reason</th><th>Last working date</th><th>Clearance</th><th>Status</th><th>Action</th></tr></thead><tbody><?php if($rows&&$rows->num_rows):while($r=$rows->fetch_assoc()):$done=(int)$r['handover_completed']+(int)$r['assets_returned']+(int)$r['access_revoked']+(int)$r['finance_clearance']+(int)$r['exit_interview'];?><tr><td><span class="hro-name"><?= $e($r['first_name'].' '.$r['last_name']) ?></span><span class="hro-sub"><?= $e($r['staff_no'].' · '.$r['department']) ?></span></td><td><?= $e($r['separation_type']) ?><span class="hro-sub"><?= $e($r['reason']?:'No reason recorded') ?></span></td><td><?= $e($r['last_working_date']) ?></td><td><span class="hro-pill <?= $done===5?'hro-done':'hro-pending' ?>"><?= $done ?>/5 checks</span></td><td><?= $e($r['status']) ?></td><td><?php if($canEdit&&$r['status']!=='Completed'):?><a class="hro-btn hro-muted" href="?edit=<?= (int)$r['id'] ?>"><i class="fas fa-pen"></i> Update</a><?php else:?>—<?php endif;?></td></tr><?php endwhile;else:?><tr><td colspan="6" style="text-align:center;padding:32px;color:#77869a">No separation cases have been recorded.</td></tr><?php endif;?></tbody></table></div></section></div></div>
