<?php
require_once __DIR__.'/../config/config.php'; require_once __DIR__.'/../includes/session.php'; require_once __DIR__.'/../includes/auth.php';
require_login(); require_module_access($conn,'procurement','view');
function pcnt(mysqli $c,string $s):int{$q=$c->query($s);return $q?(int)($q->fetch_assoc()['total']??0):0;}
$pending=pcnt($conn,"SELECT COUNT(*) total FROM purchase_orders WHERE status='Pending'");
$approved=pcnt($conn,"SELECT COUNT(*) total FROM purchase_orders WHERE status='Approved'");
$partial=pcnt($conn,"SELECT COUNT(*) total FROM purchase_orders WHERE status='Partial'");
$suppliers=pcnt($conn,"SELECT COUNT(*) total FROM suppliers");
$canCreate=can_module_action($conn,'procurement','create'); $canApprove=can_module_action($conn,'procurement','approve');
include __DIR__.'/../includes/header.php'; include __DIR__.'/../includes/sidebar.php'; ?>
<style>
.pd2{padding:28px 24px 42px;background:#f5f7fb;min-height:calc(100vh - 60px)}.ps2{max-width:1500px;margin:auto}.poh{position:relative;overflow:hidden;background:linear-gradient(135deg,#0b3d91 0%,#1261c9 55%,#13a8b8 100%);color:#fff;border-radius:22px;padding:30px 32px;display:flex;justify-content:space-between;align-items:center;gap:20px;margin-bottom:22px;box-shadow:0 16px 38px rgba(16,77,153,.18)}.poh h1{margin:5px 0;font-size:28px}.poh p{margin:0;color:rgba(255,255,255,.8);font-size:14px}.poh:before,.poh:after{content:"";position:absolute;border-radius:50%;background:rgba(255,255,255,.07);pointer-events:none}.poh:before{width:260px;height:260px;right:-90px;top:-150px}.poh:after{width:130px;height:130px;right:150px;bottom:-105px}.poh>div{position:relative;z-index:1}.pok{font-size:11px;text-transform:uppercase;letter-spacing:1.8px;font-weight:800;color:#bfe8ff}.pom{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:16px;margin-bottom:22px}.poc{background:#fff;border:1px solid #e7ebf2;border-radius:14px;padding:20px;box-shadow:0 4px 14px rgba(31,45,61,.05)}.poc small{display:block;color:#7b8798;text-transform:uppercase;font-size:10px;font-weight:800}.poc strong{font-size:28px;color:#25324a}.pog{display:grid;grid-template-columns:minmax(0,2fr) minmax(260px,1fr);gap:18px}.pop{background:#fff;border:1px solid #e7ebf2;border-radius:14px;overflow:hidden;box-shadow:0 4px 16px rgba(31,45,61,.05)}.poph{padding:16px 20px;border-bottom:1px solid #edf0f5}.popb{padding:20px}.pol{display:grid;grid-template-columns:1fr 1fr;gap:12px}.pol a{padding:18px;border:1px solid #e7ebf2;border-radius:12px;text-decoration:none;color:#344054}.pol a:hover{background:#f5f9fd;text-decoration:none}.pol i{color:#075b9d;margin-right:10px}@media(max-width:900px){.pog{grid-template-columns:1fr}.pom{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.pd2{padding:18px 12px}.poh{flex-direction:column;align-items:flex-start;padding:24px 20px;border-radius:17px}.poh h1{font-size:24px}.pom{grid-template-columns:1fr}.pol{grid-template-columns:1fr}}
</style>
<div class="pd2"><div class="ps2"><div class="poh"><div><div class="pok">Procurement</div><h1>Procurement Dashboard</h1><p>Control suppliers, purchase orders, receiving and payables.</p></div><div><?php if($canCreate): ?><a href="create_po.php" class="btn btn-light">New Purchase Order</a><?php endif; ?></div></div>
<div class="pom"><a href="purchase_orders.php?status=Pending" class="poc text-decoration-none"><small>Pending Approval</small><strong><?= $pending ?></strong></a><a href="purchase_orders.php?status=Approved" class="poc text-decoration-none"><small>Approved POs</small><strong><?= $approved ?></strong></a><a href="purchase_orders.php?status=Partial" class="poc text-decoration-none"><small>Partial Receipts</small><strong><?= $partial ?></strong></a><a href="manage_suppliers.php" class="poc text-decoration-none"><small>Suppliers</small><strong><?= $suppliers ?></strong></a></div>
<div class="pog"><div class="pop"><div class="poph"><strong>Procurement Operations</strong></div><div class="popb"><div class="pol"><a href="purchase_orders.php"><i class="fas fa-shopping-basket"></i><strong>Purchase Orders</strong></a><a href="receive_inventory.php"><i class="fas fa-warehouse"></i><strong>Receive Inventory</strong></a><a href="manage_suppliers.php"><i class="fas fa-truck"></i><strong>Suppliers</strong></a><a href="supplier_payables.php"><i class="fas fa-file-invoice-dollar"></i><strong>Supplier Payables</strong></a></div></div></div><div class="pop"><div class="poph"><strong>Approvals</strong></div><div class="popb"><h2><?= $pending ?></h2><small class="text-muted">purchase orders pending approval</small><?php if($canApprove): ?><a href="purchase_orders.php?status=Pending" class="btn btn-primary btn-block mt-3">Review POs</a><?php endif; ?></div></div></div>
</div></div><?php include __DIR__.'/../includes/footer.php'; ?>