<?php
require_once __DIR__ . '/../config/config.php';require_once __DIR__ . '/../includes/session.php';require_once __DIR__ . '/../includes/auth.php';require_login();require_module_access($conn,'maternity','edit');require_role(['admin','doctor','nurse']);
$id=max(0,(int)($_GET['id']??$_POST['id']??0));if(!$id){header('Location:index.php');exit;}
if(empty($_SESSION['csrf_token']))$_SESSION['csrf_token']=bin2hex(random_bytes(32));$csrfToken=$_SESSION['csrf_token'];$errors=[];
$s=$conn->prepare("SELECT m.*,p.full_name,p.patient_number FROM maternity m JOIN patients p ON p.id=m.patient_id WHERE m.id=? LIMIT 1");$s->bind_param('i',$id);$s->execute();$m=$s->get_result()->fetch_assoc();$s->close();if(!$m){http_response_code(404);exit('Maternity record not found.');}
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!hash_equals($csrfToken,(string)($_POST['csrf_token']??'')))$errors[]='Security token mismatch.';
 $gravida=max(0,(int)($_POST['gravida']??0));$parity=max(0,(int)($_POST['parity']??0));$lmp=trim((string)($_POST['last_menstrual_period']??''));$edd=trim((string)($_POST['expected_delivery']??''));$notes=trim((string)($_POST['antenatal_notes']??''));
 foreach([['LMP',$lmp],['Expected delivery date',$edd]] as [$label,$date]){if($date!==''){ $d=DateTime::createFromFormat('Y-m-d',$date);if(!$d||$d->format('Y-m-d')!==$date)$errors[]=$label.' must be a valid date.';}}
 if(!$errors){$u=$conn->prepare("UPDATE maternity SET gravida=?,parity=?,last_menstrual_period=?,expected_delivery=?,antenatal_notes=? WHERE id=?");if(!$u)$errors[]=$conn->error;else{$u->bind_param('iisssi',$gravida,$parity,$lmp,$edd,$notes,$id);if($u->execute()){if(function_exists('audit'))audit('maternity_profile_update',"maternity_id={$id}");header("Location:view.php?id={$id}&updated=1");exit;} $errors[]=$u->error;$u->close();}}
 $m=array_merge($m,['gravida'=>$gravida,'parity'=>$parity,'last_menstrual_period'=>$lmp,'expected_delivery'=>$edd,'antenatal_notes'=>$notes]);
}
include __DIR__ . '/../includes/header.php';include __DIR__ . '/../includes/sidebar.php';?><style>
.hms-form-page{padding:26px 24px 44px;background:#f5f7fb;min-height:calc(100vh - 60px)}
.hms-form-shell{max-width:1450px;margin:0 auto}
.hms-form-hero{background:#fff;border:1px solid #e7ebf2;border-radius:14px;padding:21px 24px;margin-bottom:20px;box-shadow:0 4px 18px rgba(31,45,61,.06);display:flex;justify-content:space-between;align-items:center;gap:18px}
.hms-form-kicker{font-size:11px;text-transform:uppercase;letter-spacing:1.3px;font-weight:700;color:#6c7a91;margin-bottom:4px}
.hms-form-hero h1{font-size:24px;font-weight:700;color:#25324a;margin:0 0 5px}.hms-form-hero p{margin:0;color:#718096;font-size:14px}
.hms-form-card{background:#fff;border:1px solid #e7ebf2;border-radius:14px;box-shadow:0 4px 16px rgba(31,45,61,.05);overflow:hidden;margin-bottom:18px}
.hms-form-card .card-header{background:#fff;border-bottom:1px solid #edf0f5;padding:16px 20px;color:#25324a;font-weight:700}
.hms-form-card .card-body{padding:21px}
.hms-form-page label{font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:.4px;color:#667085;margin-bottom:6px}
.hms-form-page .form-control{border:1px solid #d8dee8;border-radius:8px;background:#fff;color:#344054;min-height:42px;padding:10px 12px}
.hms-form-page .form-control:focus{border-color:#4c84ff;box-shadow:0 0 0 3px rgba(76,132,255,.10);outline:0}
.hms-form-page textarea.form-control{min-height:auto}.hms-form-page .btn{border-radius:8px;font-weight:700}
.hms-form-page hr{border-color:#edf0f5}.hms-form-page .table{margin-bottom:0}.hms-form-page .table thead th{background:#f8fafc;border-top:0;color:#667085;font-size:11px;text-transform:uppercase;letter-spacing:.35px}
@media(max-width:767px){.hms-form-page{padding:18px 12px 35px}.hms-form-hero{align-items:flex-start;flex-direction:column}}
</style>
<div class="main-content"><div class="hms-form-page"><div class="hms-form-shell"><div class="hms-form-hero"><div><div class="hms-form-kicker">Maternity · Maternal Profile</div><h1>Edit ANC Profile</h1><p><?=htmlspecialchars($m['full_name'])?> · <?=htmlspecialchars($m['patient_number'])?> · <?=htmlspecialchars($m['anc_number'])?></p></div><a href="view.php?id=<?=$id?>" class="btn btn-light border">Back to Record</a></div><div class="d-flex justify-content-between align-items-center mb-4"><div><h2 class="h4 mb-1 text-gray-800"><i class="fas fa-edit text-primary mr-2"></i>Edit ANC Profile</h2><p class="text-muted mb-0"><?=htmlspecialchars($m['full_name'])?> · <?=htmlspecialchars($m['patient_number'])?> · <?=htmlspecialchars($m['anc_number'])?></p></div><a href="view.php?id=<?=$id?>" class="btn btn-light">Back to Record</a></div><?php if($errors):?><div class="alert alert-danger"><ul class="mb-0"><?php foreach($errors as $e):?><li><?=htmlspecialchars($e)?></li><?php endforeach;?></ul></div><?php endif;?><div class="hms-form-card card shadow-sm" style="max-width:1000px"><div class="card-header bg-white"><strong>Maternal Registration Details</strong></div><div class="card-body"><form method="post"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars($csrfToken)?>"><input type="hidden" name="id" value="<?=$id?>"><div class="row"><div class="col-md-3 form-group"><label>Gravida</label><input type="number" min="0" name="gravida" class="form-control" value="<?=htmlspecialchars((string)$m['gravida'])?>"></div><div class="col-md-3 form-group"><label>Parity</label><input type="number" min="0" name="parity" class="form-control" value="<?=htmlspecialchars((string)$m['parity'])?>"></div><div class="col-md-3 form-group"><label>LMP</label><input type="date" name="last_menstrual_period" class="form-control" value="<?=htmlspecialchars((string)$m['last_menstrual_period'])?>"></div><div class="col-md-3 form-group"><label>Expected Delivery</label><input type="date" name="expected_delivery" class="form-control" value="<?=htmlspecialchars((string)$m['expected_delivery'])?>"></div><div class="col-12 form-group"><label>Antenatal Notes</label><textarea name="antenatal_notes" class="form-control" rows="5"><?=htmlspecialchars((string)$m['antenatal_notes'])?></textarea></div></div><div class="d-flex justify-content-end"><a href="view.php?id=<?=$id?>" class="btn btn-light mr-2">Cancel</a><button class="btn btn-primary"><i class="fas fa-save mr-1"></i>Save Changes</button></div></form></div></div></div></div></div><?php include __DIR__ . '/../includes/footer.php'; ?>