<?php
require_once __DIR__ . '/../config/config.php';require_once __DIR__ . '/../includes/session.php';require_once __DIR__ . '/../includes/auth.php';require_login();require_module_access($conn,'maternity','view');
$id=max(0,(int)($_GET['id']??0));if(!$id){header('Location:index.php');exit;}
$s=$conn->prepare("SELECT m.*,p.id patient_id,p.full_name,p.patient_number,p.phone,p.date_of_birth FROM maternity m JOIN patients p ON p.id=m.patient_id WHERE m.id=? LIMIT 1");$s->bind_param('i',$id);$s->execute();$m=$s->get_result()->fetch_assoc();$s->close();if(!$m){http_response_code(404);exit('Maternity record not found.');}
$vis=$conn->prepare("SELECT * FROM maternity_visits WHERE maternity_id=? ORDER BY created_at DESC LIMIT 20");$vis->bind_param('i',$id);$vis->execute();$visits=$vis->get_result();$vis->close();
$del=$conn->prepare("SELECT * FROM maternity_delivery WHERE maternity_id=? ORDER BY created_at DESC LIMIT 10");$del->bind_param('i',$id);$del->execute();$deliveries=$del->get_result();$del->close();
$bab=$conn->prepare("SELECT * FROM maternity_baby WHERE maternity_id=? ORDER BY created_at DESC LIMIT 20");$bab->bind_param('i',$id);$bab->execute();$babies=$bab->get_result();$bab->close();
$canCreate=can_module_action($conn,'maternity','create');$canEdit=can_module_action($conn,'maternity','edit');
include __DIR__ . '/../includes/header.php';include __DIR__ . '/../includes/sidebar.php';?>
<div class="main-content"><div class="container-fluid pt-4">
<div class="d-flex justify-content-between align-items-center mb-4"><div><h2 class="h4 mb-1 text-gray-800"><i class="fas fa-baby text-primary mr-2"></i>Maternity Patient Record</h2><p class="text-muted mb-0"><?=htmlspecialchars($m['full_name'])?> · <?=htmlspecialchars($m['patient_number'])?> · ANC <?=htmlspecialchars($m['anc_number'])?></p></div><div><?php if($canEdit):?><a href="edit.php?id=<?=$id?>" class="btn btn-outline-primary mr-2"><i class="fas fa-edit mr-1"></i>Edit ANC Profile</a><?php endif;?><a href="../patients/patient_dashboard.php?id=<?=$m['patient_id']?>" class="btn btn-light">Patient Dashboard</a></div></div>
<div class="row mb-4"><div class="col-md-3"><div class="card shadow-sm h-100"><div class="card-body"><small class="text-muted">ANC Number</small><div class="h5 mb-0"><?=htmlspecialchars($m['anc_number'])?></div></div></div></div><div class="col-md-3"><div class="card shadow-sm h-100"><div class="card-body"><small class="text-muted">Gravida / Parity</small><div class="h5 mb-0"><?=htmlspecialchars((string)$m['gravida'])?> / <?=htmlspecialchars((string)$m['parity'])?></div></div></div></div><div class="col-md-3"><div class="card shadow-sm h-100"><div class="card-body"><small class="text-muted">LMP</small><div class="h5 mb-0"><?=!empty($m['last_menstrual_period'])?htmlspecialchars(date('d M Y',strtotime($m['last_menstrual_period']))):'—'?></div></div></div></div><div class="col-md-3"><div class="card shadow-sm h-100"><div class="card-body"><small class="text-muted">Expected Delivery</small><div class="h5 mb-0 text-primary"><?=!empty($m['expected_delivery'])?htmlspecialchars(date('d M Y',strtotime($m['expected_delivery']))):'—'?></div></div></div></div></div>
<div class="card shadow-sm mb-4"><div class="card-header bg-white d-flex justify-content-between align-items-center"><strong>Maternal Profile</strong><div><?php if($canCreate):?><a href="add.php?id=<?=$id?>" class="btn btn-sm btn-primary mr-1">New Visit</a><a href="deliveries.php" class="btn btn-sm btn-outline-primary">Record Delivery</a><?php endif;?></div></div><div class="card-body"><div class="row"><div class="col-md-4"><small class="text-muted d-block">Patient</small><strong><?=htmlspecialchars($m['full_name'])?></strong></div><div class="col-md-4"><small class="text-muted d-block">Phone</small><?=htmlspecialchars($m['phone']??'—')?></div><div class="col-md-4"><small class="text-muted d-block">Date of Birth</small><?=!empty($m['date_of_birth'])?htmlspecialchars($m['date_of_birth']):'—'?></div></div><?php if(!empty($m['antenatal_notes'])):?><hr><small class="text-muted d-block">Antenatal Notes</small><div><?=nl2br(htmlspecialchars($m['antenatal_notes']))?></div><?php endif;?></div></div>
<div class="row"><div class="col-lg-8 mb-4"><div class="card shadow-sm h-100"><div class="card-header bg-white d-flex justify-content-between"><strong>Clinical Visits</strong><a href="visit_history.php?id=<?=$id?>" class="small">View all</a></div><div class="card-body p-0"><div class="table-responsive"><table class="table table-hover mb-0"><thead><tr><th>Date</th><th>Type</th><th>BP</th><th>Weight</th><th>FHR</th><th>Notes</th></tr></thead><tbody><?php if($visits&&$visits->num_rows):while($v=$visits->fetch_assoc()):?><tr><td><?=htmlspecialchars(date('d M Y H:i',strtotime($v['created_at'])))?></td><td><span class="badge badge-info"><?=htmlspecialchars($v['visit_type'])?></span></td><td><?=htmlspecialchars($v['bp'])?></td><td><?=htmlspecialchars($v['weight'])?></td><td><?=htmlspecialchars($v['fetal_heart_rate'])?></td><td><?=nl2br(htmlspecialchars($v['notes']))?></td></tr><?php endwhile;else:?><tr><td colspan="6" class="text-center text-muted py-4">No visits recorded.</td></tr><?php endif;?></tbody></table></div></div></div></div>
<div class="col-lg-4 mb-4"><div class="card shadow-sm mb-4"><div class="card-header bg-white"><strong>Deliveries</strong></div><div class="card-body p-0"><table class="table table-sm mb-0"><tbody><?php if($deliveries&&$deliveries->num_rows):while($d=$deliveries->fetch_assoc()):?><tr><td><?=htmlspecialchars(date('d M Y',strtotime($d['delivery_time']??$d['created_at'])))?></td><td><?=htmlspecialchars($d['delivery_mode'])?></td></tr><?php endwhile;else:?><tr><td class="text-muted">No deliveries recorded.</td></tr><?php endif;?></tbody></table></div></div><div class="card shadow-sm"><div class="card-header bg-white"><strong>Newborns</strong></div><div class="card-body p-0"><table class="table table-sm mb-0"><thead><tr><th>#</th><th>Sex</th><th>Weight</th><th>APGAR</th></tr></thead><tbody><?php if($babies&&$babies->num_rows):while($b=$babies->fetch_assoc()):?><tr><td><?=htmlspecialchars($b['baby_number'])?></td><td><?=htmlspecialchars($b['gender'])?></td><td><?=htmlspecialchars($b['weight'])?></td><td><?=htmlspecialchars($b['apgar'])?></td></tr><?php endwhile;else:?><tr><td colspan="4" class="text-center text-muted">No newborn records.</td></tr><?php endif;?></tbody></table></div></div></div></div>
</div></div><?php include __DIR__ . '/../includes/footer.php'; ?>