<?php
require_once __DIR__.'/../config/config.php'; require_once __DIR__.'/../includes/session.php'; require_once __DIR__.'/../includes/auth.php'; require_login();
require_module_access($conn,'insurance','view'); if(empty($_SESSION['csrf_token']))$_SESSION['csrf_token']=bin2hex(random_bytes(32));$csrf=$_SESSION['csrf_token'];$msg='';$err='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 $a=$_POST['action']??''; require_module_access($conn,'insurance',$a==='submit'?'approve':'create');
 if(!verify_csrf_token($_POST['csrf_token']??null))$err='Invalid security token.'; else try{
  if($a==='create'){
   $inv=(int)$_POST['invoice_id']; $q=$conn->prepare("SELECT i.id,i.patient_id,i.created_at,i.total,pc.id coverage_id,pc.payer_id,pc.plan_id FROM invoices i JOIN patient_coverages pc ON pc.patient_id=i.patient_id AND pc.eligibility_status='Verified' WHERE i.id=? ORDER BY pc.is_primary DESC,pc.id DESC LIMIT 1");$q->bind_param('i',$inv);$q->execute();$v=$q->get_result()->fetch_assoc();$q->close();if(!$v)throw new Exception('Invoice has no verified patient coverage.');
   $q=$conn->prepare("SELECT COUNT(*) c FROM claim_headers WHERE invoice_id=?");$q->bind_param('i',$inv);$q->execute();$exists=(int)$q->get_result()->fetch_assoc()['c'];$q->close();if($exists)throw new Exception('A claim already exists for this invoice.');
   $num='CLM-'.date('YmdHis').'-'.random_int(100,999);$s=$conn->prepare("INSERT INTO claim_headers(claim_number,patient_id,patient_coverage_id,payer_id,plan_id,invoice_id,encounter_date,claim_status,total_claim_amount,created_by) VALUES(?,?,?,?,?,?,DATE(?), 'Draft',?,?)");$s->bind_param('siiiiisdii',$num,$v['patient_id'],$v['coverage_id'],$v['payer_id'],$v['plan_id'],$v['id'],$v['created_at'],$v['total'],$_SESSION['user_id']);$s->execute();$cid=$s->insert_id;$s->close();
   $q=$conn->prepare("SELECT id,item_name,quantity,unit_price,total FROM invoice_items WHERE invoice_id=?");$q->bind_param('i',$inv);$q->execute();$items=$q->get_result();$is=$conn->prepare("INSERT INTO claim_items(claim_id,item_type,source_table,source_id,item_name,quantity,unit_price,gross_amount,covered_amount,patient_responsibility,status) VALUES(?,?,?,?,?,?,?,?,? ,0,'Draft')");while($it=$items->fetch_assoc()){$type='Other';$gross=(float)$it['total'];$is->bind_param('issidddds',$cid,$type,$src='invoice_items',$it['id'],$it['item_name'],$it['quantity'],$it['unit_price'],$gross,$gross);$is->execute();}$is->close();$q->close();if(function_exists('audit'))audit('insurance_claim_created',"claim_id={$cid},invoice_id={$inv}");$msg='Claim created from invoice.';
  }elseif($a==='submit'){ $id=(int)$_POST['id'];$s=$conn->prepare("UPDATE claim_headers SET claim_status='Submitted',submission_date=CURDATE() WHERE id=? AND claim_status='Draft'");$s->bind_param('i',$id);$s->execute();if(!$s->affected_rows)throw new Exception('Claim is not in Draft status.');$s->close();if(function_exists('audit'))audit('insurance_claim_submitted',"claim_id={$id}");$msg='Claim submitted.';}
 }catch(Throwable $e){$err=$e->getMessage();}
}
$invoices=[];$q=$conn->query("SELECT i.id,i.created_at,i.total,p.full_name FROM invoices i JOIN patients p ON p.id=i.patient_id JOIN patient_coverages pc ON pc.patient_id=i.patient_id AND pc.eligibility_status='Verified' LEFT JOIN claim_headers ch ON ch.invoice_id=i.id WHERE ch.id IS NULL ORDER BY i.created_at DESC LIMIT 100");if($q)while($x=$q->fetch_assoc())$invoices[]=$x;
$claims=[];$q=$conn->query("SELECT ch.*,p.full_name,py.payer_name FROM claim_headers ch JOIN patients p ON p.id=ch.patient_id JOIN payers py ON py.id=ch.payer_id ORDER BY ch.created_at DESC LIMIT 100");if($q)while($x=$q->fetch_assoc())$claims[]=$x;
include __DIR__.'/../includes/header.php';include __DIR__.'/../includes/sidebar.php';?>
<div class="main-content"><div class="container-fluid p-4"><div class="card border-0 shadow-sm"><div class="card-body"><h3 class="font-weight-bold">Insurance Claims</h3><p class="text-muted">Generate claims from billed services, review and submit to payers.</p>
<?php if($err):?><div class="alert alert-danger"><?=htmlspecialchars($err)?></div><?php endif;if($msg):?><div class="alert alert-success"><?=htmlspecialchars($msg)?></div><?php endif;?>
<form method="post" class="form-inline mb-4"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars($csrf)?>"><input type="hidden" name="action" value="create"><select name="invoice_id" class="form-control mr-2" required><option value="">Select eligible invoice</option><?php foreach($invoices as $i):?><option value="<?=$i['id']?>">#<?=$i['id']?> — <?=htmlspecialchars($i['full_name'])?> — KES <?=number_format($i['total'],2)?></option><?php endforeach;?></select><button class="btn btn-primary">Generate Claim</button></form>
<div class="table-responsive"><table class="table table-hover"><thead><tr><th>Claim</th><th>Patient</th><th>Payer</th><th>Invoice</th><th>Amount</th><th>Status</th><th>Action</th></tr></thead><tbody><?php foreach($claims as $c):?><tr><td><?=htmlspecialchars($c['claim_number'])?></td><td><?=htmlspecialchars($c['full_name'])?></td><td><?=htmlspecialchars($c['payer_name'])?></td><td>#<?=htmlspecialchars($c['invoice_id'])?></td><td>KES <?=number_format($c['total_claim_amount'],2)?></td><td><?=htmlspecialchars($c['claim_status'])?></td><td><?php if($c['claim_status']==='Draft'):?><form method="post"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars($csrf)?>"><input type="hidden" name="action" value="submit"><input type="hidden" name="id" value="<?=$c['id']?>"><button class="btn btn-sm btn-success">Submit</button></form><?php endif;?></td></tr><?php endforeach;?></tbody></table></div>
</div></div></div>