<?php
require_once __DIR__.'/../config/config.php';require_once __DIR__.'/../includes/session.php';require_once __DIR__.'/../includes/auth.php';require_login();require_module_access($conn,'insurance','view');
if(empty($_SESSION['csrf_token']))$_SESSION['csrf_token']=bin2hex(random_bytes(32));$csrf=$_SESSION['csrf_token'];$msg='';$err='';
if($_SERVER['REQUEST_METHOD']==='POST'){ $a=$_POST['action']??'';require_module_access($conn,'insurance',$a==='match'?'approve':'create');if(!verify_csrf_token($_POST['csrf_token']??null))$err='Invalid security token.';else try{
if($a==='create'){$payer=(int)$_POST['payer_id'];$ref=trim($_POST['reference_number']);$date=$_POST['payment_date'];$amt=(float)$_POST['amount'];$method=$_POST['payment_method'];$s=$conn->prepare("INSERT INTO remittances(payer_id,reference_number,payment_date,amount_received,payment_method,bank_reference,notes) VALUES(?,?,?,?,?,?,?)");$bank=trim($_POST['bank_reference']);$notes=trim($_POST['notes']);$s->bind_param('issdsss',$payer,$ref,$date,$amt,$method,$bank,$notes);$s->execute();$s->close();if(function_exists('audit'))audit('insurance_remittance_created',"reference={$ref},amount={$amt}");$msg='Remittance recorded.';
}elseif($a==='match'){$rid=(int)$_POST['remittance_id'];$cid=(int)$_POST['claim_id'];$paid=(float)$_POST['paid_amount'];$s=$conn->prepare("SELECT r.payer_id,r.amount_received,ch.payer_id claim_payer FROM remittances r JOIN claim_headers ch ON ch.id=? WHERE r.id=?");$s->bind_param('ii',$cid,$rid);$s->execute();$v=$s->get_result()->fetch_assoc();$s->close();if(!$v||$v['payer_id']!=$v['claim_payer'])throw new Exception('Remittance and claim payer do not match.');
$s=$conn->prepare("INSERT INTO remittance_items(remittance_id,claim_id,approved_amount,paid_amount,remittance_status,remarks) SELECT ?,id,total_approved_amount,?,CASE WHEN ? >= total_approved_amount THEN 'Matched' ELSE 'Partial' END,? FROM claim_headers WHERE id=?");$remark=trim($_POST['remarks']);$s->bind_param('iidsi',$rid,$cid,$paid,$remark,$cid);$s->execute();$s->close();$s=$conn->prepare("UPDATE claim_headers SET total_paid_amount=total_paid_amount+?,claim_status=CASE WHEN total_paid_amount+? >= total_approved_amount AND total_approved_amount>0 THEN 'Paid' ELSE 'Partially Approved' END WHERE id=?");$s->bind_param('ddi',$paid,$paid,$cid);$s->execute();$s->close();if(function_exists('audit'))audit('insurance_remittance_matched',"remittance_id={$rid},claim_id={$cid},paid={$paid}");$msg='Remittance matched to claim.';
}}catch(Throwable $e){$err=$e->getMessage();}}
$payers=[];$q=$conn->query("SELECT id,payer_name FROM payers WHERE active=1 ORDER BY payer_name");if($q)while($x=$q->fetch_assoc())$payers[]=$x;
$claims=[];$q=$conn->query("SELECT id,claim_number,payer_id,total_approved_amount FROM claim_headers WHERE claim_status IN ('Approved','Partially Approved','Submitted','Under Review') ORDER BY created_at DESC LIMIT 100");if($q)while($x=$q->fetch_assoc())$claims[]=$x;
$rem=[];$q=$conn->query("SELECT r.*,p.payer_name,COALESCE(SUM(ri.paid_amount),0) matched FROM remittances r JOIN payers p ON p.id=r.payer_id LEFT JOIN remittance_items ri ON ri.remittance_id=r.id GROUP BY r.id ORDER BY r.payment_date DESC,r.id DESC LIMIT 100");if($q)while($x=$q->fetch_assoc())$rem[]=$x;
include __DIR__.'/../includes/header.php';include __DIR__.'/../includes/sidebar.php';?>
<div class="main-content"><div class="container-fluid p-4"><div class="card border-0 shadow-sm"><div class="card-body"><div class="hms-module-hero mb-4"><div><div class="hms-module-kicker">Insurance &amp; SHA</div><h1>Remittances &amp; Reconciliation</h1><p>Record payer receipts and match them against submitted claims.</p></div></div>
<?php if($err):?><div class="alert alert-danger"><?=htmlspecialchars($err)?></div><?php endif;if($msg):?><div class="alert alert-success"><?=htmlspecialchars($msg)?></div><?php endif;?>
<form method="post" class="row mb-4"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars($csrf)?>"><input type="hidden" name="action" value="create"><div class="col-md-2"><label>Payer</label><select name="payer_id" class="form-control" required><?php foreach($payers as $p):?><option value="<?=$p['id']?>"><?=htmlspecialchars($p['payer_name'])?></option><?php endforeach;?></select></div><div class="col-md-2"><label>Reference</label><input name="reference_number" class="form-control" required></div><div class="col-md-2"><label>Date</label><input type="date" name="payment_date" class="form-control" value="<?=date('Y-m-d')?>" required></div><div class="col-md-2"><label>Amount</label><input type="number" step=".01" name="amount" class="form-control" required></div><div class="col-md-2"><label>Method</label><select name="payment_method" class="form-control"><option>Bank</option><option>Cheque</option><option>Transfer</option><option>Cash</option><option>Other</option></select></div><div class="col-md-2"><label>Bank Ref.</label><input name="bank_reference" class="form-control"></div><div class="col-12 mt-2"><input name="notes" class="form-control" placeholder="Notes"><button class="btn btn-primary mt-2">Record Remittance</button></div></form>
<h5>Open Claims</h5><div class="table-responsive"><table class="table table-hover"><thead><tr><th>Claim</th><th>Payer</th><th>Approved</th><th>Match Payment</th></tr></thead><tbody><?php foreach($claims as $c):?><tr><td><?=htmlspecialchars($c['claim_number'])?></td><td><?=htmlspecialchars($c['payer_id'])?></td><td>KES <?=number_format($c['total_approved_amount'],2)?></td><td><form method="post" class="form-inline"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars($csrf)?>"><input type="hidden" name="action" value="match"><input type="hidden" name="claim_id" value="<?=$c['id']?>"><select name="remittance_id" class="form-control form-control-sm mr-1" required><option value="">Remittance</option><?php foreach($rem as $r):?><option value="<?=$r['id']?>"><?=htmlspecialchars($r['reference_number'])?> — <?=number_format($r['amount_received'],2)?></option><?php endforeach;?></select><input name="paid_amount" type="number" step=".01" class="form-control form-control-sm mr-1" placeholder="Paid" required><input name="remarks" class="form-control form-control-sm mr-1" placeholder="Remarks"><button class="btn btn-sm btn-success">Match</button></form></td></tr><?php endforeach;?></tbody></table></div>
<h5>Remittances</h5><table class="table"><thead><tr><th>Reference</th><th>Payer</th><th>Date</th><th>Received</th><th>Matched</th></tr></thead><tbody><?php foreach($rem as $r):?><tr><td><?=htmlspecialchars($r['reference_number'])?></td><td><?=htmlspecialchars($r['payer_name'])?></td><td><?=htmlspecialchars($r['payment_date'])?></td><td>KES <?=number_format($r['amount_received'],2)?></td><td>KES <?=number_format($r['matched'],2)?></td></tr><?php endforeach;?></tbody></table>
</div></div></div>
<?php include __DIR__ . '/../includes/footer.php'; ?>
