<?php
require_once __DIR__.'/../config/config.php';require_once __DIR__.'/../includes/session.php';require_once __DIR__.'/../includes/auth.php';
require_login();require_module_access($conn,'emergency','view');
$canCreate=can_module_action($conn,'emergency','create');$canEdit=can_module_action($conn,'emergency','edit');$csrf=csrf_token();$error='';$message='';
$triage=['Immediate','Very Urgent','Urgent','Standard','Non-Urgent'];$arrivals=['Walk-in','Ambulance','Police','Referral','Other'];$statuses=['Waiting','Under Assessment','Treatment','Admitted','Discharged','Transferred','Left Before Assessment','Cancelled'];
$validNumber=static function($v,$min,$max):bool{return $v===''|| (is_numeric($v)&&(float)$v>=$min&&(float)$v<=$max);};
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!verify_csrf_token($_POST['csrf_token']??null))$error='Your security token expired. Refresh the page and try again.';
 else{
  $action=(string)($_POST['action']??'create');
  if($action==='create'){
   if(!$canCreate){http_response_code(403);exit('Forbidden: emergency create permission required.');}
   $patientId=(int)($_POST['patient_id']??0);$arrival=(string)($_POST['arrival_mode']??'Walk-in');$complaint=trim((string)($_POST['chief_complaint']??''));$level=(string)($_POST['triage_level']??'Urgent');$notes=trim((string)($_POST['triage_notes']??''));$temp=trim((string)($_POST['temperature_c']??''));$sys=trim((string)($_POST['systolic_bp']??''));$dia=trim((string)($_POST['diastolic_bp']??''));$pulse=trim((string)($_POST['pulse_bpm']??''));$resp=trim((string)($_POST['respiratory_rate']??''));$spo2=trim((string)($_POST['oxygen_saturation']??''));$pain=trim((string)($_POST['pain_score']??''));$clinician=(int)($_POST['assigned_clinician_id']??0);
   if($patientId<1||$complaint===''||strlen($complaint)>1000||strlen($notes)>1500||!in_array($arrival,$arrivals,true)||!in_array($level,$triage,true))$error='Choose a patient, arrival mode and triage level, and enter the chief complaint.';
   elseif(!$validNumber($temp,25,45)||!$validNumber($sys,40,300)||!$validNumber($dia,20,200)||!$validNumber($pulse,1,300)||!$validNumber($resp,1,100)||!$validNumber($spo2,0,100)||!$validNumber($pain,0,10))$error='One or more vital signs are outside the permitted range.';
   else{
    $conn->begin_transaction();
    try{
     $p=$conn->prepare('SELECT id FROM patients WHERE id=? FOR UPDATE');if(!$p)throw new RuntimeException('patient prepare failed');$p->bind_param('i',$patientId);$p->execute();$patient=$p->get_result()->fetch_assoc();$p->close();if(!$patient)throw new InvalidArgumentException('Patient record was not found.');
     if($clinician>0){$u=$conn->prepare('SELECT id FROM users WHERE id=? LIMIT 1');if(!$u)throw new RuntimeException('clinician prepare failed');$u->bind_param('i',$clinician);$u->execute();$user=$u->get_result()->fetch_assoc();$u->close();if(!$user)throw new InvalidArgumentException('Selected clinician account was not found.');}
     $creator=(int)($_SESSION['user_id']??0);$visitNo='ER-'.date('Ymd').'-'.strtoupper(bin2hex(random_bytes(3)));$visitType='Emergency';$clinic='Emergency/Casualty';$visitStatus='In Progress';$visit=$conn->prepare('INSERT INTO visits (visit_number,patient_id,visit_date,visit_time,visit_type,clinic_category,triage_priority,status,created_by) VALUES (?, ?, CURDATE(), CURTIME(), ?, ?, ?, ?, ?)');if(!$visit)throw new RuntimeException('visit prepare failed');$priority=$level==='Immediate'||$level==='Very Urgent'?'Emergency':($level==='Urgent'?'Urgent':'Routine');$visit->bind_param('sissssi',$visitNo,$patientId,$visitType,$clinic,$priority,$visitStatus,$creator);$visit->execute();$visitId=(int)$conn->insert_id;$visit->close();
     $tempV=$temp!==''?(float)$temp:null;$sysV=$sys!==''?(int)$sys:null;$diaV=$dia!==''?(int)$dia:null;$pulseV=$pulse!==''?(int)$pulse:null;$respV=$resp!==''?(int)$resp:null;$spo2V=$spo2!==''?(float)$spo2:null;$painV=$pain!==''?(int)$pain:null;$notesV=$notes!==''?$notes:null;$clinicianV=$clinician>0?$clinician:null;
     $sql='INSERT INTO emergency_cases (patient_id,visit_id,arrival_mode,chief_complaint,triage_level,triage_notes,temperature_c,systolic_bp,diastolic_bp,pulse_bpm,respiratory_rate,oxygen_saturation,pain_score,assigned_clinician_id,status,triaged_by,created_by,updated_by,triaged_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,\'Waiting\',?,?,?,NOW())';
     $st=$conn->prepare($sql);if(!$st)throw new RuntimeException('emergency case prepare failed');$st->bind_param('iissssdi iiiidi iii', $patientId,$visitId,$arrival,$complaint,$level,$notesV,$tempV,$sysV,$diaV,$pulseV,$respV,$spo2V,$painV,$clinicianV,$creator,$creator,$creator);$st->execute();$caseId=(int)$conn->insert_id;$st->close();
     if(function_exists('audit'))audit('emergency_case_created','case_id='.$caseId.',visit_id='.$visitId.',triage='.$level);$conn->commit();$message='Emergency case registered. Visit number: '.$visitNo.'.';
    }catch(Throwable $ex){$conn->rollback();if($ex instanceof InvalidArgumentException)$error=$ex->getMessage();else{error_log('Emergency intake failed: '.$ex->getMessage());$error='Emergency case could not be saved. Check that the visit and emergency migrations have been applied.';}}
   }
  }elseif($action==='update'){
   if(!$canEdit){http_response_code(403);exit('Forbidden: emergency edit permission required.');}
   $id=(int)($_POST['id']??0);$status=(string)($_POST['status']??'Waiting');$clinician=(int)($_POST['assigned_clinician_id']??0);$notes=trim((string)($_POST['disposition_notes']??''));
   if($id<1||!in_array($status,$statuses,true)||strlen($notes)>1500)$error='Choose a valid case status and keep disposition notes within 1,500 characters.';
   else{
    try{$conn->begin_transaction();$st=$conn->prepare('SELECT status FROM emergency_cases WHERE id=? FOR UPDATE');if(!$st)throw new RuntimeException('case lock prepare failed');$st->bind_param('i',$id);$st->execute();$existing=$st->get_result()->fetch_assoc();$st->close();if(!$existing)throw new InvalidArgumentException('Emergency case not found.');if(in_array($existing['status'],['Discharged','Transferred','Left Before Assessment','Cancelled'],true)&&$status!==$existing['status'])throw new InvalidArgumentException('A closed case cannot be reopened from this screen.');$clinicianV=$clinician>0?$clinician:null;$notesV=$notes!==''?$notes:null;$actor=(int)($_SESSION['user_id']??0);$closed=in_array($status,['Discharged','Transferred','Left Before Assessment','Cancelled'],true);$sql='UPDATE emergency_cases SET status=?,assigned_clinician_id=?,disposition_notes=?,updated_by=?,closed_at=IF(?=1,COALESCE(closed_at,NOW()),NULL) WHERE id=?';$up=$conn->prepare($sql);if(!$up)throw new RuntimeException('case update prepare failed');$closedInt=$closed?1:0;$up->bind_param('sisiii',$status,$clinicianV,$notesV,$actor,$closedInt,$id);$up->execute();$up->close();$visitStatus=$status==='Admitted'?'In Progress':(in_array($status,['Discharged','Transferred','Left Before Assessment','Cancelled'],true)?'Completed':'In Progress');$v=$conn->prepare('UPDATE visits v JOIN emergency_cases e ON e.visit_id=v.id SET v.status=? WHERE e.id=?');if(!$v)throw new RuntimeException('visit update prepare failed');$v->bind_param('si',$visitStatus,$id);$v->execute();$v->close();if(function_exists('audit'))audit('emergency_case_updated','case_id='.$id.',status='.$status);$conn->commit();$message='Emergency case updated.';
    }catch(Throwable $ex){$conn->rollback();if($ex instanceof InvalidArgumentException)$error=$ex->getMessage();else{error_log('Emergency update failed: '.$ex->getMessage());$error='Emergency case could not be updated.';}}
   }
  }
 }
}
$patients=$conn->query('SELECT id,patient_number,full_name,age,gender FROM patients ORDER BY full_name');
$users=$conn->query('SELECT id,full_name FROM users ORDER BY full_name');
$rows=$conn->query("SELECT e.*,p.patient_number,p.full_name,p.age,p.gender,v.visit_number,u.full_name clinician_name FROM emergency_cases e JOIN patients p ON p.id=e.patient_id JOIN visits v ON v.id=e.visit_id LEFT JOIN users u ON u.id=e.assigned_clinician_id ORDER BY FIELD(e.status,'Waiting','Under Assessment','Treatment','Admitted','Discharged','Transferred','Left Before Assessment','Cancelled'),FIELD(e.triage_level,'Immediate','Very Urgent','Urgent','Standard','Non-Urgent'),e.arrived_at");
$summary=$conn->query("SELECT COUNT(*) total,SUM(status IN ('Waiting','Under Assessment','Treatment')) open_count,SUM(triage_level IN ('Immediate','Very Urgent') AND status IN ('Waiting','Under Assessment','Treatment')) critical_count FROM emergency_cases");$counts=$summary?$summary->fetch_assoc():['total'=>0,'open_count'=>0,'critical_count'=>0];
$e=static fn($v)=>htmlspecialchars((string)($v??''),ENT_QUOTES,'UTF-8');include __DIR__.'/../includes/header.php';include __DIR__.'/../includes/sidebar.php';
?>
<style>
.er-page{padding:26px 22px 48px;background:#f3f6fb;min-height:calc(100vh - 75px)}.er-wrap{max-width:1500px;margin:auto}.er-hero{padding:25px 28px;border-radius:18px;color:#fff;background:linear-gradient(125deg,#7f1d1d,#b42318 60%,#e56b3f);margin-bottom:18px;display:flex;justify-content:space-between;gap:14px;align-items:center;flex-wrap:wrap}.er-hero h2{margin:0;color:#fff;font-size:1.7rem;font-weight:800}.er-hero p{margin:7px 0 0;color:#ffe3d9}.er-card,.er-metric{background:#fff;border:1px solid #e1e8f0;border-radius:15px;box-shadow:0 5px 20px #1428460d;margin-bottom:17px;overflow:hidden}.er-head{padding:15px 19px;border-bottom:1px solid #e9eef4;font-weight:800;color:#172b45}.er-metrics{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:13px;margin-bottom:17px}.er-metric{padding:17px}.er-metric small{display:block;color:#68778b;text-transform:uppercase;font-size:.68rem;font-weight:800}.er-metric strong{display:block;font-size:1.5rem;color:#172b45;margin-top:6px}.er-form{padding:19px;display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.er-field label{display:block;font-size:.67rem;text-transform:uppercase;font-weight:800;color:#65748a;margin-bottom:6px}.er-field input,.er-field select,.er-field textarea{width:100%;border:1px solid #d6e0eb;border-radius:9px;padding:10px;background:#fff}.er-wide{grid-column:1/-1}.er-btn{border:0;border-radius:9px;padding:10px 13px;font-weight:800;display:inline-flex;align-items:center;gap:7px;text-decoration:none;cursor:pointer}.er-primary{background:#9f1d16;color:#fff}.er-muted{background:#edf3fa;color:#24415f}.er-alert{padding:12px 15px;border-radius:9px;margin-bottom:14px;font-weight:700}.er-error{background:#fff1f1;color:#a11}.er-success{background:#ecfdf5;color:#087443}.er-tablewrap{overflow:auto}.er-table{width:100%;border-collapse:collapse;min-width:1200px}.er-table th,.er-table td{text-align:left;padding:11px 12px;border-bottom:1px solid #edf1f5;font-size:.8rem;vertical-align:top}.er-table th{background:#f7f9fc;color:#68778b;text-transform:uppercase;font-size:.65rem}.er-name{font-weight:800;color:#172b45}.er-sub{display:block;color:#77869a;font-size:.72rem;margin-top:3px}.er-pill{display:inline-block;padding:5px 8px;border-radius:99px;background:#edf2f7;color:#475569;font-size:.65rem;font-weight:800}.er-immediate{background:#fee2e2;color:#991b1b}.er-urgent{background:#ffedd5;color:#9a3412}.er-open{background:#fff7e6;color:#996300}.er-closed{background:#e9fbf1;color:#087443}.er-inline{display:grid;gap:6px;min-width:190px}.er-inline select,.er-inline textarea{width:100%;border:1px solid #d6e0eb;border-radius:7px;padding:7px}.er-vitals{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}@media(max-width:1100px){.er-form{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:560px){.er-page{padding:16px 10px}.er-form,.er-metrics,.er-vitals{grid-template-columns:1fr}.er-hero{padding:20px}}
</style>
<div class="er-page"><div class="er-wrap"><section class="er-hero"><div><div style="font-size:.68rem;letter-spacing:.14em;text-transform:uppercase;font-weight:800;margin-bottom:6px">Emergency services · Time-critical care</div><h2>Emergency / Casualty</h2><p>Register emergency arrivals, record triage observations and manage the active queue.</p></div></section>
<?php if($error!==''):?><div class="er-alert er-error"><?= $e($error) ?></div><?php endif;?><?php if($message!==''):?><div class="er-alert er-success"><?= $e($message) ?></div><?php endif;?>
<section class="er-metrics"><div class="er-metric"><small>Total cases</small><strong><?= (int)($counts['total']??0) ?></strong></div><div class="er-metric"><small>Active emergency queue</small><strong><?= (int)($counts['open_count']??0) ?></strong></div><div class="er-metric"><small>Immediate / very urgent</small><strong><?= (int)($counts['critical_count']??0) ?></strong></div></section>
<?php if($canCreate):?><section class="er-card"><div class="er-head">Emergency intake &amp; triage</div><form method="post" class="er-form"><input type="hidden" name="csrf_token" value="<?= $e($csrf) ?>"><input type="hidden" name="action" value="create">
<div class="er-field er-wide"><label>Registered patient *</label><select name="patient_id" required><option value="">Select patient record</option><?php if($patients):while($p=$patients->fetch_assoc()):?><option value="<?= (int)$p['id'] ?>"><?= $e($p['patient_number'].' · '.$p['full_name'].' · '.$p['gender'].' · Age '.$p['age']) ?></option><?php endwhile;$patients->data_seek(0);endif;?></select><small>Register an unregistered walk-in at Reception first.</small></div>
<div class="er-field"><label>Arrival mode</label><select name="arrival_mode"><?php foreach($arrivals as $a):?><option value="<?= $e($a) ?>"><?= $e($a) ?></option><?php endforeach;?></select></div><div class="er-field"><label>Triage priority *</label><select name="triage_level"><?php foreach($triage as $t):?><option value="<?= $e($t) ?>" <?= $t==='Urgent'?'selected':'' ?>><?= $e($t) ?></option><?php endforeach;?></select></div><div class="er-field"><label>Assign clinician</label><select name="assigned_clinician_id"><option value="0">Unassigned</option><?php if($users):while($u=$users->fetch_assoc()):?><option value="<?= (int)$u['id'] ?>"><?= $e($u['full_name']) ?></option><?php endwhile;$users->data_seek(0);endif;?></select></div>
<div class="er-field er-wide"><label>Chief complaint / presenting problem *</label><textarea name="chief_complaint" required maxlength="1000" rows="2"></textarea></div><div class="er-field er-wide"><label>Triage notes</label><textarea name="triage_notes" maxlength="1500" rows="2"></textarea></div>
<div class="er-wide"><div class="er-head" style="padding:0 0 10px;border:0">Initial observations (optional; enter measured values only)</div><div class="er-vitals"><div class="er-field"><label>Temperature °C</label><input type="number" step=".1" min="25" max="45" name="temperature_c"></div><div class="er-field"><label>Systolic BP</label><input type="number" min="40" max="300" name="systolic_bp"></div><div class="er-field"><label>Diastolic BP</label><input type="number" min="20" max="200" name="diastolic_bp"></div><div class="er-field"><label>Pulse / min</label><input type="number" min="1" max="300" name="pulse_bpm"></div><div class="er-field"><label>Respiratory rate</label><input type="number" min="1" max="100" name="respiratory_rate"></div><div class="er-field"><label>Oxygen saturation %</label><input type="number" step=".1" min="0" max="100" name="oxygen_saturation"></div><div class="er-field"><label>Pain score (0–10)</label><input type="number" min="0" max="10" name="pain_score"></div></div></div>
<div class="er-wide"><button class="er-btn er-primary" type="submit"><i class="fas fa-truck-medical"></i> Register emergency case</button></div></form></section><?php endif;?>
<section class="er-card"><div class="er-head">Casualty queue · highest acuity first</div><div class="er-tablewrap"><table class="er-table"><thead><tr><th>Patient / visit</th><th>Arrival</th><th>Presenting problem / triage notes</th><th>Triage</th><th>Observations</th><th>Assigned clinician</th><th>Status / disposition</th></tr></thead><tbody><?php if($rows&&$rows->num_rows):while($r=$rows->fetch_assoc()):$priorityClass=in_array($r['triage_level'],['Immediate','Very Urgent'],true)?'er-immediate':($r['triage_level']==='Urgent'?'er-urgent':'');$closed=in_array($r['status'],['Discharged','Transferred','Left Before Assessment','Cancelled'],true);?><tr><td><span class="er-name"><?= $e($r['full_name']) ?></span><span class="er-sub"><?= $e($r['patient_number']) ?> · <?= $e($r['visit_number']) ?></span><span class="er-sub"><?= $e($r['age']) ?> yrs · <?= $e($r['gender']) ?></span></td><td><?= $e($r['arrived_at']) ?><span class="er-sub"><?= $e($r['arrival_mode']) ?></span></td><td><?= $e($r['chief_complaint']) ?><span class="er-sub"><?= $e($r['triage_notes']?:'No triage notes') ?></span></td><td><span class="er-pill <?= $priorityClass ?>"><?= $e($r['triage_level']) ?></span></td><td><?= $e($r['temperature_c']!==null?$r['temperature_c'].' °C':'—') ?><span class="er-sub">BP <?= $e($r['systolic_bp']!==null?$r['systolic_bp'].'/'.$r['diastolic_bp']:'—') ?> · Pulse <?= $e($r['pulse_bpm']??'—') ?></span><span class="er-sub">RR <?= $e($r['respiratory_rate']??'—') ?> · SpO₂ <?= $e($r['oxygen_saturation']??'—') ?> · Pain <?= $e($r['pain_score']??'—') ?></span></td><td><?= $e($r['clinician_name']?:'Unassigned') ?></td><td><?php if($canEdit&&!$closed):?><form method="post" class="er-inline"><input type="hidden" name="csrf_token" value="<?= $e($csrf) ?>"><input type="hidden" name="action" value="update"><input type="hidden" name="id" value="<?= (int)$r['id'] ?>"><select name="status"><?php foreach($statuses as $st):?><option value="<?= $e($st) ?>" <?= $r['status']===$st?'selected':'' ?>><?= $e($st) ?></option><?php endforeach;?></select><select name="assigned_clinician_id"><option value="0">Unassigned</option><?php if($users):while($u=$users->fetch_assoc()):?><option value="<?= (int)$u['id'] ?>" <?= ((int)($r['assigned_clinician_id']??0)===(int)$u['id'])?'selected':'' ?>><?= $e($u['full_name']) ?></option><?php endwhile;$users->data_seek(0);endif;?></select><textarea name="disposition_notes" rows="2" maxlength="1500" placeholder="Disposition / handover notes"><?= $e($r['disposition_notes']??'') ?></textarea><button class="er-btn er-primary" type="submit">Update</button></form><?php else:?><span class="er-pill <?= $closed?'er-closed':'er-open' ?>"><?= $e($r['status']) ?></span><span class="er-sub"><?= $e($r['disposition_notes']?:'') ?></span><?php endif;?></td></tr><?php endwhile;else:?><tr><td colspan="7" style="text-align:center;padding:35px;color:#77869a">No emergency cases recorded yet.</td></tr><?php endif;?></tbody></table></div></section></div></div>
